(rule
 (target lui_components_web.ml)
 (deps
  ../../../lg/lui/lui_melange.state
  (source_tree ../../../lg/lui/backend)
  (source_tree ../lg/components)
  (source_tree lg/components)
  %{bin:lg})
 (action
  (run
   %{bin:lg}
   --target melange
   --compile-files-from ../../../lg/lui/lui_melange.state
   ../../../lg/lui/backend/retained
   ../../../lg/lui/backend/web
   ../lg/components
   lg/components
   -o %{target})))

(melange.emit
 (target lui-components-web)
 (alias web)
 (module_systems es6)
 (modules lui_components_web web_bootstrap)
 (preprocess (pps melange.ppx))
 (compile_flags -w -27-32-37-39-69)
 (libraries
  lg.edn-backend
  lg.edn-backend.melange
  lg.runtime
  lg.rrbvec
  lui.web.dom
  melange-webapi))
