(install
 (section lib)
 (package lui)
 (source_trees lg))

(library
 (name lui)
 (public_name lui)
 (modules))

(library
 (name lui_states)
 (public_name lui.states)
 (modules))

(install
 (section lib)
 (package lui)
 (files
  (lg/lui/lui_native.state as states/lui_native.state)
  (lg/lui/lui_native_backends.state as states/lui_native_backends.state)
  (lg/lui/lui_melange.state as states/lui_melange.state)
  (lg/lui/lui_melange_backends.state as states/lui_melange_backends.state)))
