(install
 (section lib)
 (package lui)
 (files
  (lg/lui/protocol.lgi as lg/lui/protocol.lgi)
  (lg/lui/protocol.cljc as lg/lui/protocol.cljc)
  (lg/lui/wire.lgi as lg/lui/wire.lgi)
  (lg/lui/wire.cljc as lg/lui/wire.cljc)
  (lg/lui/runtime.lgi as lg/lui/runtime.lgi)
  (lg/lui/runtime.cljc as lg/lui/runtime.cljc)
  (lg/lui/app.lgi as lg/lui/app.lgi)
  (lg/lui/app.cljc as lg/lui/app.cljc)
  (lg/lui/ui.lgi as lg/lui/ui.lgi)
  (lg/lui/ui.cljc as lg/lui/ui.cljc)
  (lg/lui/elements.cljc as lg/lui/elements.cljc)
  (lg/lui/macros.cljc as lg/lui/macros.cljc)
  (lg/lui/dynamic.lgi as lg/lui/dynamic.lgi)
  (lg/lui/dynamic.cljc as lg/lui/dynamic.cljc)
  (lg/lui/backend/retained.lgi as lg/lui/backend/retained.lgi)
  (lg/lui/backend/retained.cljc as lg/lui/backend/retained.cljc)
  (lg/lui/backend/apple.lgi as lg/lui/backend/apple.lgi)
  (lg/lui/backend/apple.cljc as lg/lui/backend/apple.cljc)
  (lg/lui/backend/flutter.lgi as lg/lui/backend/flutter.lgi)
  (lg/lui/backend/flutter.cljc as lg/lui/backend/flutter.cljc)
  (lg/lui/backend/web.lgi as lg/lui/backend/web.lgi)
  (lg/lui/backend/web.cljc as lg/lui/backend/web.cljc)
  (lg/lui/host/ctypes.lgi as lg/lui/host/ctypes.lgi)
  (lg/lui/host/ctypes.cljc as lg/lui/host/ctypes.cljc)
  (lg/lui/host/apple.lgi as lg/lui/host/apple.lgi)
  (lg/lui/host/apple.cljc as lg/lui/host/apple.cljc)))
