(rule
 (target lui_web.ml)
 (deps
  ../../lg/lui/lui_melange.state
  (source_tree ../../lg/lui/backend)
  (source_tree ../../examples/todos/lg/todos)
  (source_tree lg/todos)
  %{bin:lg})
 (action
  (run
   %{bin:lg}
   --target melange
   --compile-files-from ../../lg/lui/lui_melange.state
   ../../lg/lui/backend/retained
   ../../lg/lui/backend/web
   ../../examples/todos/lg/todos
   lg/todos
   -o %{target})))

(melange.emit
 (target lui-web)
 (alias web)
 (module_systems es6)
 (modules lui_web)
 (preprocess (pps melange.ppx))
 (compile_flags -w -27-32-37-39-69)
 (libraries
  lg.edn-backend
  lg.edn-backend.melange
  lg.runtime
  lg.rrbvec
  melange-webapi))
