(rule
 (target lui_web_chunk.ml)
 (deps
  %{lib:lg:stdlib/lg_stdlib_melange.state}
  %{lib:signal-lg.sources:lg/signal/core.lgi}
  %{lib:signal-lg.sources:lg/signal/core.cljc}
  ../../lg/lui/protocol.lgi
  ../../lg/lui/protocol.cljc
  ../../lg/lui/runtime.lgi
  ../../lg/lui/runtime.cljc
  ../../lg/lui/ui.lgi
  ../../lg/lui/ui.cljc
  ../../lg/lui/app.lgi
  ../../lg/lui/app.cljc
  ../../lg/lui/elements.cljc
  ../../lg/lui/macros.cljc
  ../../lg/lui/dynamic.lgi
  ../../lg/lui/dynamic.cljc
  ../../lg/lui/backend/retained.lgi
  ../../lg/lui/backend/retained.cljc
  ../../lg/lui/backend/web.lgi
  ../../lg/lui/backend/web.cljc
  ../../examples/todos/lg/todos/model.lgi
  ../../examples/todos/lg/todos/model.cljc
  ../../examples/todos/lg/todos/view.lgi
  ../../examples/todos/lg/todos/view.cljc
  ../../examples/todos/lg/todos/app.lgi
  ../../examples/todos/lg/todos/app.cljc
  lg/todos/web_main.lgi
  lg/todos/web_main.cljc
  %{bin:lg})
 (action
  (run
   %{bin:lg}
   --target melange
   --compile-files-from %{lib:lg:stdlib/lg_stdlib_melange.state}
   %{lib:signal-lg.sources:lg/signal/core.lgi}
   %{lib:signal-lg.sources:lg/signal/core.cljc}
   %{dep:../../lg/lui/protocol.lgi}
   %{dep:../../lg/lui/protocol.cljc}
   %{dep:../../lg/lui/runtime.lgi}
   %{dep:../../lg/lui/runtime.cljc}
   %{dep:../../lg/lui/ui.lgi}
   %{dep:../../lg/lui/ui.cljc}
   %{dep:../../lg/lui/app.lgi}
   %{dep:../../lg/lui/app.cljc}
   %{dep:../../lg/lui/elements.cljc}
   %{dep:../../lg/lui/macros.cljc}
   %{dep:../../lg/lui/dynamic.lgi}
   %{dep:../../lg/lui/dynamic.cljc}
   %{dep:../../lg/lui/backend/retained.lgi}
   %{dep:../../lg/lui/backend/retained.cljc}
   %{dep:../../lg/lui/backend/web.lgi}
   %{dep:../../lg/lui/backend/web.cljc}
   %{dep:../../examples/todos/lg/todos/model.lgi}
   %{dep:../../examples/todos/lg/todos/model.cljc}
   %{dep:../../examples/todos/lg/todos/view.lgi}
   %{dep:../../examples/todos/lg/todos/view.cljc}
   %{dep:../../examples/todos/lg/todos/app.lgi}
   %{dep:../../examples/todos/lg/todos/app.cljc}
   %{dep:lg/todos/web_main.lgi}
   %{dep:lg/todos/web_main.cljc}
   -o %{target})))

(rule
 (target lui_web.ml)
 (deps %{lib:lg:stdlib/lg_stdlib_melange.ml} lui_web_chunk.ml)
 (action
  (with-stdout-to %{target}
   (progn
    (cat %{lib:lg:stdlib/lg_stdlib_melange.ml})
    (cat %{dep:lui_web_chunk.ml})))))

(melange.emit
 (target lui-web)
 (alias web)
 (module_systems es6)
 (modules lui_web)
 (preprocess (pps melange.ppx))
 (compile_flags -w -27-32-37-39-69)
 (libraries
  lg.edn-backend
  lg.edn-backend.melange
  lg.runtime
  lg.rrbvec
  melange-webapi))
