(library
 (name components_bridge)
 (modules components_bridge)
 (libraries lui ocaml-signal gallery_app)
 (wrapped false))

(rule
 (enabled_if
  (= %{system} "macosx"))
 (target liblui_components.dylib)
 (deps
  ../../../platform/native/lui_ocaml_bridge.c
  components_bridge.cmxa
  ../../gallery/gallery_app.cmxa
  ../../../src/lui.cmxa)
 (action
  (run
   sh
   -c
   "ocamlfind ocamlopt -linkpkg -linkall -package ocaml-signal \
      %{dep:../../../src/lui.cmxa} %{dep:../../gallery/gallery_app.cmxa} \
      %{dep:components_bridge.cmxa} \
      -output-complete-obj -o components_bridge_complete.o && \
    cc -shared -o %{target} \
      %{dep:../../../platform/native/lui_ocaml_bridge.c} \
      components_bridge_complete.o \
      -I\"$(ocamlfind ocamlc -where)\" -lpthread")))
