(rule
 (target gallery_bridge.ml)
 (deps
  ../../../lg/lui/lui_native.state
  (source_tree ../../../lg/lui/backend)
  (source_tree ../lg/components)
  (source_tree .)
  %{bin:lg})
 (action
  (run
   %{bin:lg}
   --target native
   --compile-files-from ../../../lg/lui/lui_native.state
   ../../../lg/lui/backend/retained
   ../../../lg/lui/backend/flutter
   ../lg/components
   .
   -o %{target})))

(rule
 (target gallery_bridge_complete.o)
 (deps gallery_bridge.ml)
 (action
  (run
   ocamlfind ocamlopt
   -package lg.edn-backend.native,lg.runtime,lg.rrbvec
   -linkpkg
   -output-complete-obj
   -o %{target}
   %{dep:gallery_bridge.ml})))

(rule
 (target liblui_components.dylib)
 (deps
  gallery_bridge_complete.o
  ../../../platform/flutter/native/lui_ocaml_bridge.c)
 (action
  (run
   clang
   -dynamiclib
   -o %{target}
   %{dep:../../../platform/flutter/native/lui_ocaml_bridge.c}
   %{dep:gallery_bridge_complete.o}
   -I %{ocaml_where}
   -lpthread)))
