(rule
 (targets lui_native.ml lui_native.state)
 (deps
  %{lib:signal-lg.states:signal_native.state}
  (source_tree .)
  %{bin:lg})
 (action
  (run
   %{bin:lg}
   --target native
   --compile-files-from-state
   %{lib:signal-lg.states:signal_native.state}
   lui_native.state
   -o lui_native.ml)))

(rule
 (targets lui_melange.ml lui_melange.state)
 (deps
  %{lib:signal-lg.states:signal_melange.state}
  (source_tree .)
  %{bin:lg})
 (action
  (run
   %{bin:lg}
   --target melange
   --compile-files-from-state
   %{lib:signal-lg.states:signal_melange.state}
   lui_melange.state
   -o lui_melange.ml)))
