// Generated from schema/components.json. Do not edit by hand.
#[allow(clippy::match_same_arms)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum NodeKind {
    Root,
    Row,
    Column,
    Grid,
    Stack,
    EdgeInset,
    Overlay,
    ViewThatFits,
    Panel,
    Card,
    Alert,
    Bubble,
    Box,
    Text,
    Heading,
    Paragraph,
    Label,
    Button,
    ToggleButton,
    Toggle,
    RadioGroup,
    Radio,
    Slider,
    NumberStepper,
    TextField,
    SecureField,
    Input,
    SearchField,
    Textarea,
    Checkbox,
    SwitchControl,
    Progress,
    Divider,
    Scroll,
    ListContainer,
    VirtualList,
    Tabs,
    BottomTabs,
    BottomTab,
    ButtonGroup,
    ToggleGroup,
    Spacer,
    Spinner,
    Icon,
    Select,
    Combobox,
    DropdownMenu,
    ContextMenu,
    MenuItem,
    MenuTrigger,
    ListItem,
    Avatar,
    Image,
    MediaSurface,
    Stepper,
    Step,
    Timeline,
    TimelineItem,
    InputGroup,
    InputGroupActions,
    Breadcrumb,
    Pagination,
    Accordion,
    Table,
    TableRow,
    TableCell,
    Tree,
    Resizable,
    Split,
    Dialog,
    Drawer,
    Sheet,
    Tooltip,
    Toast,
    Toolbar,
    StatusBar,
    ListSection,
    ListSectionHeader,
    ListSectionFooter,
    SwipeActions,
    SwipeAction,
    FilePicker,
    Kbd,
    Link,
    FileImage,
    FilePreview,
    Br,
    Popover,
}

impl NodeKind {
    pub fn from_wire(name: &str) -> Option<NodeKind> {
        match name {
            "root" => Some(NodeKind::Root),
            "row" => Some(NodeKind::Row),
            "column" => Some(NodeKind::Column),
            "grid" => Some(NodeKind::Grid),
            "stack" => Some(NodeKind::Stack),
            "edge-inset" => Some(NodeKind::EdgeInset),
            "overlay" => Some(NodeKind::Overlay),
            "view-that-fits" => Some(NodeKind::ViewThatFits),
            "panel" => Some(NodeKind::Panel),
            "card" => Some(NodeKind::Card),
            "alert" => Some(NodeKind::Alert),
            "bubble" => Some(NodeKind::Bubble),
            "box" => Some(NodeKind::Box),
            "text" => Some(NodeKind::Text),
            "heading" => Some(NodeKind::Heading),
            "paragraph" => Some(NodeKind::Paragraph),
            "label" => Some(NodeKind::Label),
            "button" => Some(NodeKind::Button),
            "toggle-button" => Some(NodeKind::ToggleButton),
            "toggle" => Some(NodeKind::Toggle),
            "radio-group" => Some(NodeKind::RadioGroup),
            "radio" => Some(NodeKind::Radio),
            "slider" => Some(NodeKind::Slider),
            "number-stepper" => Some(NodeKind::NumberStepper),
            "text-field" => Some(NodeKind::TextField),
            "secure-field" => Some(NodeKind::SecureField),
            "input" => Some(NodeKind::Input),
            "search-field" => Some(NodeKind::SearchField),
            "textarea" => Some(NodeKind::Textarea),
            "checkbox" => Some(NodeKind::Checkbox),
            "switch" => Some(NodeKind::SwitchControl),
            "progress" => Some(NodeKind::Progress),
            "divider" => Some(NodeKind::Divider),
            "scroll" => Some(NodeKind::Scroll),
            "list" => Some(NodeKind::ListContainer),
            "virtual-list" => Some(NodeKind::VirtualList),
            "tabs" => Some(NodeKind::Tabs),
            "bottom-tabs" => Some(NodeKind::BottomTabs),
            "bottom-tab" => Some(NodeKind::BottomTab),
            "button-group" => Some(NodeKind::ButtonGroup),
            "toggle-group" => Some(NodeKind::ToggleGroup),
            "spacer" => Some(NodeKind::Spacer),
            "spinner" => Some(NodeKind::Spinner),
            "icon" => Some(NodeKind::Icon),
            "select" => Some(NodeKind::Select),
            "combobox" => Some(NodeKind::Combobox),
            "dropdown-menu" => Some(NodeKind::DropdownMenu),
            "context-menu" => Some(NodeKind::ContextMenu),
            "menu-item" => Some(NodeKind::MenuItem),
            "menu-trigger" => Some(NodeKind::MenuTrigger),
            "list-item" => Some(NodeKind::ListItem),
            "avatar" => Some(NodeKind::Avatar),
            "image" => Some(NodeKind::Image),
            "media-surface" => Some(NodeKind::MediaSurface),
            "stepper" => Some(NodeKind::Stepper),
            "step" => Some(NodeKind::Step),
            "timeline" => Some(NodeKind::Timeline),
            "timeline-item" => Some(NodeKind::TimelineItem),
            "input-group" => Some(NodeKind::InputGroup),
            "input-group-actions" => Some(NodeKind::InputGroupActions),
            "breadcrumb" => Some(NodeKind::Breadcrumb),
            "pagination" => Some(NodeKind::Pagination),
            "accordion" => Some(NodeKind::Accordion),
            "table" => Some(NodeKind::Table),
            "table-row" => Some(NodeKind::TableRow),
            "table-cell" => Some(NodeKind::TableCell),
            "tree" => Some(NodeKind::Tree),
            "resizable" => Some(NodeKind::Resizable),
            "split" => Some(NodeKind::Split),
            "dialog" => Some(NodeKind::Dialog),
            "drawer" => Some(NodeKind::Drawer),
            "sheet" => Some(NodeKind::Sheet),
            "tooltip" => Some(NodeKind::Tooltip),
            "toast" => Some(NodeKind::Toast),
            "toolbar" => Some(NodeKind::Toolbar),
            "status-bar" => Some(NodeKind::StatusBar),
            "list-section" => Some(NodeKind::ListSection),
            "list-section-header" => Some(NodeKind::ListSectionHeader),
            "list-section-footer" => Some(NodeKind::ListSectionFooter),
            "swipe-actions" => Some(NodeKind::SwipeActions),
            "swipe-action" => Some(NodeKind::SwipeAction),
            "file-picker" => Some(NodeKind::FilePicker),
            "kbd" => Some(NodeKind::Kbd),
            "link" => Some(NodeKind::Link),
            "file-image" => Some(NodeKind::FileImage),
            "file-preview" => Some(NodeKind::FilePreview),
            "br" => Some(NodeKind::Br),
            "popover" => Some(NodeKind::Popover),
            _ => None,
        }
    }

    pub fn wire_name(self) -> &'static str {
        match self {
            NodeKind::Root => "root",
            NodeKind::Row => "row",
            NodeKind::Column => "column",
            NodeKind::Grid => "grid",
            NodeKind::Stack => "stack",
            NodeKind::EdgeInset => "edge-inset",
            NodeKind::Overlay => "overlay",
            NodeKind::ViewThatFits => "view-that-fits",
            NodeKind::Panel => "panel",
            NodeKind::Card => "card",
            NodeKind::Alert => "alert",
            NodeKind::Bubble => "bubble",
            NodeKind::Box => "box",
            NodeKind::Text => "text",
            NodeKind::Heading => "heading",
            NodeKind::Paragraph => "paragraph",
            NodeKind::Label => "label",
            NodeKind::Button => "button",
            NodeKind::ToggleButton => "toggle-button",
            NodeKind::Toggle => "toggle",
            NodeKind::RadioGroup => "radio-group",
            NodeKind::Radio => "radio",
            NodeKind::Slider => "slider",
            NodeKind::NumberStepper => "number-stepper",
            NodeKind::TextField => "text-field",
            NodeKind::SecureField => "secure-field",
            NodeKind::Input => "input",
            NodeKind::SearchField => "search-field",
            NodeKind::Textarea => "textarea",
            NodeKind::Checkbox => "checkbox",
            NodeKind::SwitchControl => "switch",
            NodeKind::Progress => "progress",
            NodeKind::Divider => "divider",
            NodeKind::Scroll => "scroll",
            NodeKind::ListContainer => "list",
            NodeKind::VirtualList => "virtual-list",
            NodeKind::Tabs => "tabs",
            NodeKind::BottomTabs => "bottom-tabs",
            NodeKind::BottomTab => "bottom-tab",
            NodeKind::ButtonGroup => "button-group",
            NodeKind::ToggleGroup => "toggle-group",
            NodeKind::Spacer => "spacer",
            NodeKind::Spinner => "spinner",
            NodeKind::Icon => "icon",
            NodeKind::Select => "select",
            NodeKind::Combobox => "combobox",
            NodeKind::DropdownMenu => "dropdown-menu",
            NodeKind::ContextMenu => "context-menu",
            NodeKind::MenuItem => "menu-item",
            NodeKind::MenuTrigger => "menu-trigger",
            NodeKind::ListItem => "list-item",
            NodeKind::Avatar => "avatar",
            NodeKind::Image => "image",
            NodeKind::MediaSurface => "media-surface",
            NodeKind::Stepper => "stepper",
            NodeKind::Step => "step",
            NodeKind::Timeline => "timeline",
            NodeKind::TimelineItem => "timeline-item",
            NodeKind::InputGroup => "input-group",
            NodeKind::InputGroupActions => "input-group-actions",
            NodeKind::Breadcrumb => "breadcrumb",
            NodeKind::Pagination => "pagination",
            NodeKind::Accordion => "accordion",
            NodeKind::Table => "table",
            NodeKind::TableRow => "table-row",
            NodeKind::TableCell => "table-cell",
            NodeKind::Tree => "tree",
            NodeKind::Resizable => "resizable",
            NodeKind::Split => "split",
            NodeKind::Dialog => "dialog",
            NodeKind::Drawer => "drawer",
            NodeKind::Sheet => "sheet",
            NodeKind::Tooltip => "tooltip",
            NodeKind::Toast => "toast",
            NodeKind::Toolbar => "toolbar",
            NodeKind::StatusBar => "status-bar",
            NodeKind::ListSection => "list-section",
            NodeKind::ListSectionHeader => "list-section-header",
            NodeKind::ListSectionFooter => "list-section-footer",
            NodeKind::SwipeActions => "swipe-actions",
            NodeKind::SwipeAction => "swipe-action",
            NodeKind::FilePicker => "file-picker",
            NodeKind::Kbd => "kbd",
            NodeKind::Link => "link",
            NodeKind::FileImage => "file-image",
            NodeKind::FilePreview => "file-preview",
            NodeKind::Br => "br",
            NodeKind::Popover => "popover",
        }
    }

    pub fn is_container(self) -> bool {
        matches!(
            self,
            NodeKind::Root
                | NodeKind::Row
                | NodeKind::Column
                | NodeKind::Grid
                | NodeKind::Stack
                | NodeKind::EdgeInset
                | NodeKind::Overlay
                | NodeKind::ViewThatFits
                | NodeKind::Panel
                | NodeKind::Card
                | NodeKind::Alert
                | NodeKind::Bubble
                | NodeKind::Box
                | NodeKind::Text
                | NodeKind::Heading
                | NodeKind::Paragraph
                | NodeKind::Label
                | NodeKind::Button
                | NodeKind::RadioGroup
                | NodeKind::Scroll
                | NodeKind::ListContainer
                | NodeKind::VirtualList
                | NodeKind::Tabs
                | NodeKind::BottomTabs
                | NodeKind::BottomTab
                | NodeKind::ButtonGroup
                | NodeKind::ToggleGroup
                | NodeKind::DropdownMenu
                | NodeKind::ContextMenu
                | NodeKind::MenuItem
                | NodeKind::MenuTrigger
                | NodeKind::ListItem
                | NodeKind::Stepper
                | NodeKind::Timeline
                | NodeKind::InputGroup
                | NodeKind::InputGroupActions
                | NodeKind::Breadcrumb
                | NodeKind::Pagination
                | NodeKind::Accordion
                | NodeKind::Table
                | NodeKind::TableRow
                | NodeKind::Tree
                | NodeKind::Resizable
                | NodeKind::Split
                | NodeKind::Dialog
                | NodeKind::Drawer
                | NodeKind::Sheet
                | NodeKind::Toast
                | NodeKind::Toolbar
                | NodeKind::ListSection
                | NodeKind::ListSectionHeader
                | NodeKind::ListSectionFooter
                | NodeKind::SwipeActions
                | NodeKind::FilePicker
                | NodeKind::Link
                | NodeKind::Popover
                // Option children feed `option_items`; the picker never
                // paints them as elements.
                | NodeKind::Select
                | NodeKind::Combobox
        )
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Property {
    TextValue,
    Enabled,
    Gap,
    MainAlignment,
    CrossAlignment,
    GrowValue,
    GridColumns,
    PaddingValue,
    PaddingHorizontal,
    PaddingVertical,
    BackgroundValue,
    ForegroundValue,
    BorderColorValue,
    BorderWidth,
    CornerRadius,
    WidthValue,
    HeightValue,
    MinWidth,
    MaxWidth,
    MinHeight,
    MaxHeight,
    ContainerRelativeFrameValue,
    ContainerRelativeFrameInset,
    PlaceholderValue,
    AccessibilityLabel,
    AccessibilityIdentifier,
    StyleClass,
    HeadingLevel,
    Checked,
    ProgressValue,
    OrientationValue,
    PlacementValue,
    SizeValue,
    IconName,
    VariantValue,
    InlineIconName,
    IconPlacementValue,
    Selected,
    Autofocus,
    SubmitOnEnter,
    LongPressEnabled,
    ChangeEnabled,
    ToggleEnabled,
    PressEnabled,
    SubmitEnabled,
    DoublePressEnabled,
    AppearEnabled,
    ImageIdValue,
    SurfaceIdValue,
    ActiveIndex,
    TitleValue,
    DescriptionValue,
    MetaValue,
    IndicatorValue,
    Connector,
    SourceX,
    SourceY,
    SourceWidth,
    SourceHeight,
    AnchorValue,
    AnchorAlignmentValue,
    AnchorOffset,
    TooltipDelay,
    DurationValue,
    TextAlignment,
    RoleValue,
    TreeLevel,
    Expanded,
    ResizeDuration,
    ResizeEasing,
    ResizeOrigin,
    ThemeValue,
    ThemeMode,
    KeyValue,
    SeparatorValue,
    StyleValue,
    ScrollTarget,
    ScrollAnchor,
    ScrollToken,
    ScrollAnimated,
    TrackVisibleRange,
    EdgeValue,
    PickerRequest,
    PickerTypes,
    PickerMultiple,
    PickerSource,
    PickerCompletion,
    MinValue,
    MaxValue,
    StepValue,
    Detents,
    Sizing,
    PathValue,
    UrlValue,
    MaxPixelSize,
    ImageFitValue,
    Visible,
    AlignmentValue,
    PointerEnabled,
    DataAttrs,
    As,
    AltValue,
    LoadingValue,
    ReferrerPolicy,
    TargetValue,
    Opacity,
    DisplayValue,
    TooltipText,
    TooltipKeys,
    InputType,
    PickerAccept,
    PickerDirectory,
    PopupX,
    PopupY,
    AvailableHeight,
}

impl Property {
    pub fn from_wire(name: &str) -> Option<Property> {
        match name {
            "text" => Some(Property::TextValue),
            "enabled" => Some(Property::Enabled),
            "gap" => Some(Property::Gap),
            "main" => Some(Property::MainAlignment),
            "cross" => Some(Property::CrossAlignment),
            "grow" => Some(Property::GrowValue),
            "columns" => Some(Property::GridColumns),
            "padding" => Some(Property::PaddingValue),
            "padding-horizontal" => Some(Property::PaddingHorizontal),
            "padding-vertical" => Some(Property::PaddingVertical),
            "background" => Some(Property::BackgroundValue),
            "foreground" => Some(Property::ForegroundValue),
            "border-color" => Some(Property::BorderColorValue),
            "border-width" => Some(Property::BorderWidth),
            "corner-radius" => Some(Property::CornerRadius),
            "width" => Some(Property::WidthValue),
            "height" => Some(Property::HeightValue),
            "min-width" => Some(Property::MinWidth),
            "max-width" => Some(Property::MaxWidth),
            "min-height" => Some(Property::MinHeight),
            "max-height" => Some(Property::MaxHeight),
            "container-relative-frame" => Some(Property::ContainerRelativeFrameValue),
            "container-relative-frame-inset" => Some(Property::ContainerRelativeFrameInset),
            "placeholder" => Some(Property::PlaceholderValue),
            "accessibility-label" => Some(Property::AccessibilityLabel),
            "accessibility-identifier" => Some(Property::AccessibilityIdentifier),
            "style-class" => Some(Property::StyleClass),
            "heading-level" => Some(Property::HeadingLevel),
            "checked" => Some(Property::Checked),
            "value" => Some(Property::ProgressValue),
            "orientation" => Some(Property::OrientationValue),
            "placement" => Some(Property::PlacementValue),
            "size" => Some(Property::SizeValue),
            "name" => Some(Property::IconName),
            "variant" => Some(Property::VariantValue),
            "icon" => Some(Property::InlineIconName),
            "icon-placement" => Some(Property::IconPlacementValue),
            "selected" => Some(Property::Selected),
            "autofocus" => Some(Property::Autofocus),
            "submit-on-enter" => Some(Property::SubmitOnEnter),
            "long-press-enabled" => Some(Property::LongPressEnabled),
            "change-enabled" => Some(Property::ChangeEnabled),
            "toggle-enabled" => Some(Property::ToggleEnabled),
            "press-enabled" => Some(Property::PressEnabled),
            "submit-enabled" => Some(Property::SubmitEnabled),
            "double-press-enabled" => Some(Property::DoublePressEnabled),
            "appear-enabled" => Some(Property::AppearEnabled),
            "image" => Some(Property::ImageIdValue),
            "surface" => Some(Property::SurfaceIdValue),
            "active" => Some(Property::ActiveIndex),
            "title" => Some(Property::TitleValue),
            "description" => Some(Property::DescriptionValue),
            "meta" => Some(Property::MetaValue),
            "indicator" => Some(Property::IndicatorValue),
            "connector" => Some(Property::Connector),
            "source-x" => Some(Property::SourceX),
            "source-y" => Some(Property::SourceY),
            "source-width" => Some(Property::SourceWidth),
            "source-height" => Some(Property::SourceHeight),
            "anchor" => Some(Property::AnchorValue),
            "anchor-alignment" => Some(Property::AnchorAlignmentValue),
            "anchor-offset" => Some(Property::AnchorOffset),
            "tooltip-delay" => Some(Property::TooltipDelay),
            "duration" => Some(Property::DurationValue),
            "text-alignment" => Some(Property::TextAlignment),
            "role" => Some(Property::RoleValue),
            "tree-level" => Some(Property::TreeLevel),
            "expanded" => Some(Property::Expanded),
            "resize-duration" => Some(Property::ResizeDuration),
            "resize-easing" => Some(Property::ResizeEasing),
            "resize-origin" => Some(Property::ResizeOrigin),
            "theme" => Some(Property::ThemeValue),
            "theme-mode" => Some(Property::ThemeMode),
            "key" => Some(Property::KeyValue),
            "separator" => Some(Property::SeparatorValue),
            "style" => Some(Property::StyleValue),
            "scroll-target" => Some(Property::ScrollTarget),
            "scroll-anchor" => Some(Property::ScrollAnchor),
            "scroll-token" => Some(Property::ScrollToken),
            "scroll-animated" => Some(Property::ScrollAnimated),
            "track-visible-range" => Some(Property::TrackVisibleRange),
            "edge" => Some(Property::EdgeValue),
            "request" => Some(Property::PickerRequest),
            "types" => Some(Property::PickerTypes),
            "multiple" => Some(Property::PickerMultiple),
            "source" => Some(Property::PickerSource),
            "completion" => Some(Property::PickerCompletion),
            "min" => Some(Property::MinValue),
            "max" => Some(Property::MaxValue),
            "step" => Some(Property::StepValue),
            "detents" => Some(Property::Detents),
            "sizing" => Some(Property::Sizing),
            "path" => Some(Property::PathValue),
            "url" => Some(Property::UrlValue),
            "max-pixel-size" => Some(Property::MaxPixelSize),
            "image-fit" => Some(Property::ImageFitValue),
            "visible" => Some(Property::Visible),
            "alignment" => Some(Property::AlignmentValue),
            "pointer-enabled" => Some(Property::PointerEnabled),
            "data-attrs" => Some(Property::DataAttrs),
            "as" => Some(Property::As),
            "alt" => Some(Property::AltValue),
            "loading" => Some(Property::LoadingValue),
            "referrer-policy" => Some(Property::ReferrerPolicy),
            "target" => Some(Property::TargetValue),
            "opacity" => Some(Property::Opacity),
            "display" => Some(Property::DisplayValue),
            "tooltip" => Some(Property::TooltipText),
            "tooltip-keys" => Some(Property::TooltipKeys),
            "input-type" => Some(Property::InputType),
            "accept" => Some(Property::PickerAccept),
            "directory" => Some(Property::PickerDirectory),
            "x" => Some(Property::PopupX),
            "y" => Some(Property::PopupY),
            "available-height" => Some(Property::AvailableHeight),
            _ => None,
        }
    }

    pub fn wire_name(self) -> &'static str {
        match self {
            Property::TextValue => "text",
            Property::Enabled => "enabled",
            Property::Gap => "gap",
            Property::MainAlignment => "main",
            Property::CrossAlignment => "cross",
            Property::GrowValue => "grow",
            Property::GridColumns => "columns",
            Property::PaddingValue => "padding",
            Property::PaddingHorizontal => "padding-horizontal",
            Property::PaddingVertical => "padding-vertical",
            Property::BackgroundValue => "background",
            Property::ForegroundValue => "foreground",
            Property::BorderColorValue => "border-color",
            Property::BorderWidth => "border-width",
            Property::CornerRadius => "corner-radius",
            Property::WidthValue => "width",
            Property::HeightValue => "height",
            Property::MinWidth => "min-width",
            Property::MaxWidth => "max-width",
            Property::MinHeight => "min-height",
            Property::MaxHeight => "max-height",
            Property::ContainerRelativeFrameValue => "container-relative-frame",
            Property::ContainerRelativeFrameInset => "container-relative-frame-inset",
            Property::PlaceholderValue => "placeholder",
            Property::AccessibilityLabel => "accessibility-label",
            Property::AccessibilityIdentifier => "accessibility-identifier",
            Property::StyleClass => "style-class",
            Property::HeadingLevel => "heading-level",
            Property::Checked => "checked",
            Property::ProgressValue => "value",
            Property::OrientationValue => "orientation",
            Property::PlacementValue => "placement",
            Property::SizeValue => "size",
            Property::IconName => "name",
            Property::VariantValue => "variant",
            Property::InlineIconName => "icon",
            Property::IconPlacementValue => "icon-placement",
            Property::Selected => "selected",
            Property::Autofocus => "autofocus",
            Property::SubmitOnEnter => "submit-on-enter",
            Property::LongPressEnabled => "long-press-enabled",
            Property::ChangeEnabled => "change-enabled",
            Property::ToggleEnabled => "toggle-enabled",
            Property::PressEnabled => "press-enabled",
            Property::SubmitEnabled => "submit-enabled",
            Property::DoublePressEnabled => "double-press-enabled",
            Property::AppearEnabled => "appear-enabled",
            Property::ImageIdValue => "image",
            Property::SurfaceIdValue => "surface",
            Property::ActiveIndex => "active",
            Property::TitleValue => "title",
            Property::DescriptionValue => "description",
            Property::MetaValue => "meta",
            Property::IndicatorValue => "indicator",
            Property::Connector => "connector",
            Property::SourceX => "source-x",
            Property::SourceY => "source-y",
            Property::SourceWidth => "source-width",
            Property::SourceHeight => "source-height",
            Property::AnchorValue => "anchor",
            Property::AnchorAlignmentValue => "anchor-alignment",
            Property::AnchorOffset => "anchor-offset",
            Property::TooltipDelay => "tooltip-delay",
            Property::DurationValue => "duration",
            Property::TextAlignment => "text-alignment",
            Property::RoleValue => "role",
            Property::TreeLevel => "tree-level",
            Property::Expanded => "expanded",
            Property::ResizeDuration => "resize-duration",
            Property::ResizeEasing => "resize-easing",
            Property::ResizeOrigin => "resize-origin",
            Property::ThemeValue => "theme",
            Property::ThemeMode => "theme-mode",
            Property::KeyValue => "key",
            Property::SeparatorValue => "separator",
            Property::StyleValue => "style",
            Property::ScrollTarget => "scroll-target",
            Property::ScrollAnchor => "scroll-anchor",
            Property::ScrollToken => "scroll-token",
            Property::ScrollAnimated => "scroll-animated",
            Property::TrackVisibleRange => "track-visible-range",
            Property::EdgeValue => "edge",
            Property::PickerRequest => "request",
            Property::PickerTypes => "types",
            Property::PickerMultiple => "multiple",
            Property::PickerSource => "source",
            Property::PickerCompletion => "completion",
            Property::MinValue => "min",
            Property::MaxValue => "max",
            Property::StepValue => "step",
            Property::Detents => "detents",
            Property::Sizing => "sizing",
            Property::PathValue => "path",
            Property::UrlValue => "url",
            Property::MaxPixelSize => "max-pixel-size",
            Property::ImageFitValue => "image-fit",
            Property::Visible => "visible",
            Property::AlignmentValue => "alignment",
            Property::PointerEnabled => "pointer-enabled",
            Property::DataAttrs => "data-attrs",
            Property::As => "as",
            Property::AltValue => "alt",
            Property::LoadingValue => "loading",
            Property::ReferrerPolicy => "referrer-policy",
            Property::TargetValue => "target",
            Property::Opacity => "opacity",
            Property::DisplayValue => "display",
            Property::TooltipText => "tooltip",
            Property::TooltipKeys => "tooltip-keys",
            Property::InputType => "input-type",
            Property::PickerAccept => "accept",
            Property::PickerDirectory => "directory",
            Property::PopupX => "x",
            Property::PopupY => "y",
            Property::AvailableHeight => "available-height",
        }
    }
}

/// Mirrors schema/components.json kindProperties: kinds listed here admit
/// ONLY the given kind-specific props (plus the shared/common set), instead of
/// the default "common set" behaviour for unlisted kinds. `None` means the
/// kind follows the common-property rules in the backend.
pub fn kind_property_matrix(kind: NodeKind) -> Option<&'static [Property]> {
    match kind {
        NodeKind::Accordion => Some(&[
            Property::TextValue,
            Property::Selected,
            Property::ToggleEnabled,
            Property::HeightValue,
            Property::PointerEnabled,
        ]),
        NodeKind::Stepper => Some(&[
            Property::ActiveIndex,
            Property::AccessibilityLabel,
            Property::PointerEnabled,
        ]),
        NodeKind::Step => Some(&[Property::TextValue, Property::PointerEnabled]),
        NodeKind::Timeline => Some(&[
            Property::Gap,
            Property::GrowValue,
            Property::AccessibilityLabel,
            Property::PointerEnabled,
        ]),
        NodeKind::TimelineItem => Some(&[
            Property::TitleValue,
            Property::DescriptionValue,
            Property::MetaValue,
            Property::IndicatorValue,
            Property::InlineIconName,
            Property::VariantValue,
            Property::Connector,
            Property::Selected,
            Property::PressEnabled,
            Property::PointerEnabled,
        ]),
        NodeKind::InputGroup => Some(&[
            Property::AccessibilityLabel,
            Property::WidthValue,
            Property::HeightValue,
            Property::MinWidth,
            Property::GrowValue,
            Property::PointerEnabled,
        ]),
        NodeKind::InputGroupActions => Some(&[Property::Gap, Property::PointerEnabled]),
        NodeKind::Toast => Some(&[
            Property::DurationValue,
            Property::AccessibilityLabel,
            Property::StyleClass,
            Property::DataAttrs,
            Property::PointerEnabled,
        ]),
        NodeKind::Toolbar => Some(&[
            Property::OrientationValue,
            Property::AccessibilityLabel,
            Property::Gap,
            Property::StyleClass,
            Property::DataAttrs,
            Property::PlacementValue,
            Property::PointerEnabled,
        ]),
        NodeKind::BottomTabs => Some(&[
            Property::AccessibilityLabel,
            Property::StyleClass,
            Property::DataAttrs,
            Property::GrowValue,
            Property::WidthValue,
            Property::HeightValue,
            Property::MinWidth,
            Property::MaxWidth,
            Property::MinHeight,
            Property::MaxHeight,
            Property::PointerEnabled,
        ]),
        NodeKind::BottomTab => Some(&[
            Property::TitleValue,
            Property::InlineIconName,
            Property::Selected,
            Property::Enabled,
            Property::PressEnabled,
            Property::PointerEnabled,
        ]),
        NodeKind::MenuTrigger => Some(&[
            Property::TextValue,
            Property::InlineIconName,
            Property::AccessibilityLabel,
            Property::Enabled,
            Property::ForegroundValue,
            Property::StyleClass,
            Property::DataAttrs,
            Property::PointerEnabled,
        ]),
        NodeKind::ListSection => Some(&[
            Property::KeyValue,
            Property::SeparatorValue,
            Property::PointerEnabled,
        ]),
        NodeKind::SwipeActions => Some(&[]),
        NodeKind::SwipeAction => Some(&[
            Property::TextValue,
            Property::InlineIconName,
            Property::VariantValue,
            Property::EdgeValue,
            Property::Enabled,
            Property::BackgroundValue,
            Property::PressEnabled,
            Property::PointerEnabled,
        ]),
        NodeKind::FilePicker => Some(&[
            Property::PickerRequest,
            Property::PickerTypes,
            Property::PickerMultiple,
            Property::PickerSource,
            Property::PickerCompletion,
            Property::PickerAccept,
            Property::PickerDirectory,
            Property::Enabled,
            Property::AppearEnabled,
            Property::PointerEnabled,
        ]),
        NodeKind::FilePreview => Some(&[Property::PathValue, Property::PointerEnabled]),
        NodeKind::Kbd => Some(&[
            Property::TextValue,
            Property::StyleClass,
            Property::DataAttrs,
            Property::PointerEnabled,
        ]),
        _ => None,
    }
}

/// Mirrors schema/components.json kindExtraProperties: additional props
/// admitted on top of the kind's normal set.
pub fn kind_extra_properties(kind: NodeKind) -> &'static [Property] {
    match kind {
        NodeKind::Dialog => &[Property::DescriptionValue],
        _ => &[],
    }
}
