// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Lui();
Q_GHS_KEEP_REFERENCE(qml_register_types_Lui);

class LuiPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    LuiPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Lui;
        Q_UNUSED(registration);
    }
};



#include "lui_qmlplugin_LuiPlugin.moc"
