// Generated from schema/components.json. Do not edit by hand.
package dev.lui

enum class LuiNodeKind(val wireName: String, val isContainer: Boolean) {
    root("root", true),
    row("row", true),
    column("column", true),
    grid("grid", true),
    stack("stack", true),
    edgeInset("edge-inset", true),
    overlay("overlay", true),
    viewThatFits("view-that-fits", true),
    panel("panel", true),
    card("card", true),
    alert("alert", true),
    bubble("bubble", true),
    box("box", true),
    text("text", true),
    heading("heading", true),
    paragraph("paragraph", true),
    label("label", true),
    button("button", true),
    toggleButton("toggle-button", false),
    toggle("toggle", false),
    radioGroup("radio-group", true),
    radio("radio", false),
    slider("slider", false),
    numberStepper("number-stepper", false),
    textField("text-field", false),
    secureField("secure-field", false),
    input("input", false),
    searchField("search-field", false),
    textarea("textarea", false),
    checkbox("checkbox", false),
    switchControl("switch", false),
    progress("progress", false),
    divider("divider", false),
    scroll("scroll", true),
    list("list", true),
    virtualList("virtual-list", true),
    tabs("tabs", true),
    bottomTabs("bottom-tabs", true),
    bottomTab("bottom-tab", true),
    buttonGroup("button-group", true),
    toggleGroup("toggle-group", true),
    spacer("spacer", false),
    spinner("spinner", false),
    icon("icon", false),
    select("select", true),
    combobox("combobox", true),
    dropdownMenu("dropdown-menu", true),
    contextMenu("context-menu", true),
    menuItem("menu-item", true),
    menuTrigger("menu-trigger", true),
    listItem("list-item", true),
    avatar("avatar", false),
    image("image", false),
    mediaSurface("media-surface", false),
    stepper("stepper", true),
    step("step", false),
    timeline("timeline", true),
    timelineItem("timeline-item", false),
    inputGroup("input-group", true),
    inputGroupActions("input-group-actions", true),
    breadcrumb("breadcrumb", true),
    pagination("pagination", true),
    accordion("accordion", true),
    table("table", true),
    tableRow("table-row", true),
    tableCell("table-cell", false),
    tree("tree", true),
    resizable("resizable", true),
    split("split", true),
    dialog("dialog", true),
    drawer("drawer", true),
    sheet("sheet", true),
    tooltip("tooltip", false),
    toast("toast", true),
    toolbar("toolbar", true),
    statusBar("status-bar", false),
    listSection("list-section", true),
    listSectionHeader("list-section-header", true),
    listSectionFooter("list-section-footer", true),
    swipeActions("swipe-actions", true),
    swipeAction("swipe-action", false),
    filePicker("file-picker", true),
    kbd("kbd", false),
    link("link", true),
    fileImage("file-image", false),
    filePreview("file-preview", false),
    br("br", false),
    popover("popover", true),
    ;

    companion object {
        private val byWire: Map<String, LuiNodeKind> = entries.associateBy { it.wireName }

        fun fromWire(wire: String): LuiNodeKind? = byWire[wire]
    }
}

enum class LuiProperty(val wireName: String) {
    text("text"),
    enabled("enabled"),
    gap("gap"),
    main("main"),
    cross("cross"),
    grow("grow"),
    columns("columns"),
    padding("padding"),
    paddingHorizontal("padding-horizontal"),
    paddingVertical("padding-vertical"),
    background("background"),
    foreground("foreground"),
    borderColor("border-color"),
    borderWidth("border-width"),
    cornerRadius("corner-radius"),
    width("width"),
    height("height"),
    minWidth("min-width"),
    maxWidth("max-width"),
    minHeight("min-height"),
    maxHeight("max-height"),
    containerRelativeFrame("container-relative-frame"),
    containerRelativeFrameInset("container-relative-frame-inset"),
    placeholder("placeholder"),
    accessibilityLabel("accessibility-label"),
    accessibilityIdentifier("accessibility-identifier"),
    styleClass("style-class"),
    headingLevel("heading-level"),
    checked("checked"),
    progressValue("value"),
    orientation("orientation"),
    placement("placement"),
    size("size"),
    propName("name"),
    variant("variant"),
    icon("icon"),
    iconPlacement("icon-placement"),
    selected("selected"),
    autofocus("autofocus"),
    submitOnEnter("submit-on-enter"),
    longPressEnabled("long-press-enabled"),
    changeEnabled("change-enabled"),
    toggleEnabled("toggle-enabled"),
    pressEnabled("press-enabled"),
    submitEnabled("submit-enabled"),
    doublePressEnabled("double-press-enabled"),
    appearEnabled("appear-enabled"),
    image("image"),
    surface("surface"),
    active("active"),
    title("title"),
    description("description"),
    meta("meta"),
    indicator("indicator"),
    connector("connector"),
    sourceX("source-x"),
    sourceY("source-y"),
    sourceWidth("source-width"),
    sourceHeight("source-height"),
    anchor("anchor"),
    anchorAlignment("anchor-alignment"),
    anchorOffset("anchor-offset"),
    tooltipDelay("tooltip-delay"),
    duration("duration"),
    textAlignment("text-alignment"),
    role("role"),
    treeLevel("tree-level"),
    expanded("expanded"),
    resizeDuration("resize-duration"),
    resizeEasing("resize-easing"),
    resizeOrigin("resize-origin"),
    theme("theme"),
    themeMode("theme-mode"),
    key("key"),
    separator("separator"),
    style("style"),
    scrollTarget("scroll-target"),
    scrollAnchor("scroll-anchor"),
    scrollToken("scroll-token"),
    scrollAnimated("scroll-animated"),
    trackVisibleRange("track-visible-range"),
    edge("edge"),
    request("request"),
    types("types"),
    multiple("multiple"),
    source("source"),
    completion("completion"),
    minValue("min"),
    maxValue("max"),
    stepValue("step"),
    detents("detents"),
    sizing("sizing"),
    path("path"),
    url("url"),
    maxPixelSize("max-pixel-size"),
    imageFit("image-fit"),
    visible("visible"),
    alignment("alignment"),
    pointerEnabled("pointer-enabled"),
    dataAttrs("data-attrs"),
    asTag("as"),
    alt("alt"),
    loading("loading"),
    referrerPolicy("referrer-policy"),
    target("target"),
    opacity("opacity"),
    display("display"),
    tooltip("tooltip"),
    tooltipKeys("tooltip-keys"),
    inputType("input-type"),
    pickerAccept("accept"),
    pickerDirectory("directory"),
    popupX("x"),
    popupY("y"),
    availableHeight("available-height"),
    ;

    companion object {
        private val byWire: Map<String, LuiProperty> = entries.associateBy { it.wireName }

        fun fromWire(wire: String): LuiProperty? = byWire[wire]
    }
}

/**
 * Mirrors schema/components.json kindProperties: kinds listed here admit
 * ONLY the given kind-specific props (plus the shared/common set), instead of
 * the default "common set" behaviour for unlisted kinds. Absence means the
 * kind follows the common-property rules in the backend.
 */
object LuiSchemaMatrix {
    val restrictive: Map<LuiNodeKind, Set<LuiProperty>> = mapOf(
        LuiNodeKind.accordion to setOf(LuiProperty.text, LuiProperty.selected, LuiProperty.toggleEnabled, LuiProperty.height, LuiProperty.pointerEnabled),
        LuiNodeKind.stepper to setOf(LuiProperty.active, LuiProperty.accessibilityLabel, LuiProperty.pointerEnabled),
        LuiNodeKind.step to setOf(LuiProperty.text, LuiProperty.pointerEnabled),
        LuiNodeKind.timeline to setOf(LuiProperty.gap, LuiProperty.grow, LuiProperty.accessibilityLabel, LuiProperty.pointerEnabled),
        LuiNodeKind.timelineItem to setOf(LuiProperty.title, LuiProperty.description, LuiProperty.meta, LuiProperty.indicator, LuiProperty.icon, LuiProperty.variant, LuiProperty.connector, LuiProperty.selected, LuiProperty.pressEnabled, LuiProperty.pointerEnabled),
        LuiNodeKind.inputGroup to setOf(LuiProperty.accessibilityLabel, LuiProperty.width, LuiProperty.height, LuiProperty.minWidth, LuiProperty.grow, LuiProperty.pointerEnabled),
        LuiNodeKind.inputGroupActions to setOf(LuiProperty.gap, LuiProperty.pointerEnabled),
        LuiNodeKind.toast to setOf(LuiProperty.duration, LuiProperty.accessibilityLabel, LuiProperty.styleClass, LuiProperty.dataAttrs, LuiProperty.pointerEnabled, LuiProperty.padding, LuiProperty.paddingHorizontal, LuiProperty.paddingVertical),
        LuiNodeKind.toolbar to setOf(LuiProperty.orientation, LuiProperty.accessibilityLabel, LuiProperty.gap, LuiProperty.styleClass, LuiProperty.dataAttrs, LuiProperty.placement, LuiProperty.pointerEnabled),
        LuiNodeKind.bottomTabs to setOf(LuiProperty.accessibilityLabel, LuiProperty.styleClass, LuiProperty.dataAttrs, LuiProperty.grow, LuiProperty.width, LuiProperty.height, LuiProperty.minWidth, LuiProperty.maxWidth, LuiProperty.minHeight, LuiProperty.maxHeight, LuiProperty.pointerEnabled),
        LuiNodeKind.bottomTab to setOf(LuiProperty.title, LuiProperty.icon, LuiProperty.selected, LuiProperty.enabled, LuiProperty.pressEnabled, LuiProperty.pointerEnabled),
        LuiNodeKind.menuTrigger to setOf(LuiProperty.text, LuiProperty.icon, LuiProperty.accessibilityLabel, LuiProperty.enabled, LuiProperty.foreground, LuiProperty.styleClass, LuiProperty.dataAttrs, LuiProperty.pointerEnabled),
        LuiNodeKind.listSection to setOf(LuiProperty.key, LuiProperty.separator, LuiProperty.pointerEnabled),
        LuiNodeKind.swipeActions to setOf(),
        LuiNodeKind.swipeAction to setOf(LuiProperty.text, LuiProperty.icon, LuiProperty.variant, LuiProperty.edge, LuiProperty.enabled, LuiProperty.background, LuiProperty.pressEnabled, LuiProperty.pointerEnabled),
        LuiNodeKind.filePicker to setOf(LuiProperty.request, LuiProperty.types, LuiProperty.multiple, LuiProperty.source, LuiProperty.completion, LuiProperty.pickerAccept, LuiProperty.pickerDirectory, LuiProperty.enabled, LuiProperty.appearEnabled, LuiProperty.pointerEnabled),
        LuiNodeKind.filePreview to setOf(LuiProperty.path, LuiProperty.pointerEnabled),
        LuiNodeKind.kbd to setOf(LuiProperty.text, LuiProperty.styleClass, LuiProperty.dataAttrs, LuiProperty.pointerEnabled),
    )

    val extra: Map<LuiNodeKind, Set<LuiProperty>> = mapOf(
        LuiNodeKind.dialog to setOf(LuiProperty.description),
    )
}
