// Generated from schema/components.json. Do not edit by hand.
part of 'lui_flutter_backend.dart';

enum _NodeKind {
  row,
  column,
  grid,
  stack,
  panel,
  card,
  box,
  text,
  heading,
  paragraph,
  label,
  button,
  toggleButton,
  toggle,
  radioGroup,
  radio,
  slider,
  textField,
  input,
  searchField,
  textarea,
  checkbox,
  switchControl,
  progress,
  divider,
  scroll,
  list,
  tabs,
  spacer,
  spinner,
  icon,
  select,
  combobox,
  dropdownMenu,
  menuItem,
  listItem,
  avatar,
}

_NodeKind _decodeNodeKind(Object? value) {
  if (value is! String) {
    throw const LUIBackendException('kind must be a string');
  }
  return switch (value) {
    'row' => _NodeKind.row,
    'column' => _NodeKind.column,
    'grid' => _NodeKind.grid,
    'stack' => _NodeKind.stack,
    'panel' => _NodeKind.panel,
    'card' => _NodeKind.card,
    'box' => _NodeKind.box,
    'text' => _NodeKind.text,
    'heading' => _NodeKind.heading,
    'paragraph' => _NodeKind.paragraph,
    'label' => _NodeKind.label,
    'button' => _NodeKind.button,
    'toggle-button' => _NodeKind.toggleButton,
    'toggle' => _NodeKind.toggle,
    'radio-group' => _NodeKind.radioGroup,
    'radio' => _NodeKind.radio,
    'slider' => _NodeKind.slider,
    'text-field' => _NodeKind.textField,
    'input' => _NodeKind.input,
    'search-field' => _NodeKind.searchField,
    'textarea' => _NodeKind.textarea,
    'checkbox' => _NodeKind.checkbox,
    'switch' => _NodeKind.switchControl,
    'progress' => _NodeKind.progress,
    'divider' => _NodeKind.divider,
    'scroll' => _NodeKind.scroll,
    'list' => _NodeKind.list,
    'tabs' => _NodeKind.tabs,
    'spacer' => _NodeKind.spacer,
    'spinner' => _NodeKind.spinner,
    'icon' => _NodeKind.icon,
    'select' => _NodeKind.select,
    'combobox' => _NodeKind.combobox,
    'dropdown-menu' => _NodeKind.dropdownMenu,
    'menu-item' => _NodeKind.menuItem,
    'list-item' => _NodeKind.listItem,
    'avatar' => _NodeKind.avatar,
    _ => throw const LUIBackendException('unknown node kind'),
  };
}
