// Generated from schema/components.json. Do not edit by hand.
part of 'lui_flutter_backend.dart';

enum _NodeKind {
  root,
  row,
  column,
  grid,
  stack,
  panel,
  card,
  alert,
  bubble,
  box,
  text,
  heading,
  paragraph,
  label,
  button,
  toggleButton,
  toggle,
  radioGroup,
  radio,
  slider,
  textField,
  secureField,
  input,
  searchField,
  textarea,
  checkbox,
  switchControl,
  progress,
  divider,
  scroll,
  list,
  virtualList,
  tabs,
  buttonGroup,
  toggleGroup,
  spacer,
  spinner,
  icon,
  select,
  combobox,
  dropdownMenu,
  contextMenu,
  menuItem,
  listItem,
  avatar,
  image,
  mediaSurface,
  stepper,
  step,
  timeline,
  timelineItem,
  inputGroup,
  inputGroupActions,
  breadcrumb,
  pagination,
  accordion,
  table,
  tableRow,
  tableCell,
  tree,
  resizable,
  split,
  dialog,
  drawer,
  sheet,
  tooltip,
  toast,
  toolbar,
  statusBar,
}

_NodeKind _decodeNodeKind(Object? value) {
  if (value is! String) {
    throw const LUIBackendException('kind must be a string');
  }
  return switch (value) {
    'root' => _NodeKind.root,
    'row' => _NodeKind.row,
    'column' => _NodeKind.column,
    'grid' => _NodeKind.grid,
    'stack' => _NodeKind.stack,
    'panel' => _NodeKind.panel,
    'card' => _NodeKind.card,
    'alert' => _NodeKind.alert,
    'bubble' => _NodeKind.bubble,
    'box' => _NodeKind.box,
    'text' => _NodeKind.text,
    'heading' => _NodeKind.heading,
    'paragraph' => _NodeKind.paragraph,
    'label' => _NodeKind.label,
    'button' => _NodeKind.button,
    'toggle-button' => _NodeKind.toggleButton,
    'toggle' => _NodeKind.toggle,
    'radio-group' => _NodeKind.radioGroup,
    'radio' => _NodeKind.radio,
    'slider' => _NodeKind.slider,
    'text-field' => _NodeKind.textField,
    'secure-field' => _NodeKind.secureField,
    'input' => _NodeKind.input,
    'search-field' => _NodeKind.searchField,
    'textarea' => _NodeKind.textarea,
    'checkbox' => _NodeKind.checkbox,
    'switch' => _NodeKind.switchControl,
    'progress' => _NodeKind.progress,
    'divider' => _NodeKind.divider,
    'scroll' => _NodeKind.scroll,
    'list' => _NodeKind.list,
    'virtual-list' => _NodeKind.virtualList,
    'tabs' => _NodeKind.tabs,
    'button-group' => _NodeKind.buttonGroup,
    'toggle-group' => _NodeKind.toggleGroup,
    'spacer' => _NodeKind.spacer,
    'spinner' => _NodeKind.spinner,
    'icon' => _NodeKind.icon,
    'select' => _NodeKind.select,
    'combobox' => _NodeKind.combobox,
    'dropdown-menu' => _NodeKind.dropdownMenu,
    'context-menu' => _NodeKind.contextMenu,
    'menu-item' => _NodeKind.menuItem,
    'list-item' => _NodeKind.listItem,
    'avatar' => _NodeKind.avatar,
    'image' => _NodeKind.image,
    'media-surface' => _NodeKind.mediaSurface,
    'stepper' => _NodeKind.stepper,
    'step' => _NodeKind.step,
    'timeline' => _NodeKind.timeline,
    'timeline-item' => _NodeKind.timelineItem,
    'input-group' => _NodeKind.inputGroup,
    'input-group-actions' => _NodeKind.inputGroupActions,
    'breadcrumb' => _NodeKind.breadcrumb,
    'pagination' => _NodeKind.pagination,
    'accordion' => _NodeKind.accordion,
    'table' => _NodeKind.table,
    'table-row' => _NodeKind.tableRow,
    'table-cell' => _NodeKind.tableCell,
    'tree' => _NodeKind.tree,
    'resizable' => _NodeKind.resizable,
    'split' => _NodeKind.split,
    'dialog' => _NodeKind.dialog,
    'drawer' => _NodeKind.drawer,
    'sheet' => _NodeKind.sheet,
    'tooltip' => _NodeKind.tooltip,
    'toast' => _NodeKind.toast,
    'toolbar' => _NodeKind.toolbar,
    'status-bar' => _NodeKind.statusBar,
    _ => throw const LUIBackendException('unknown node kind'),
  };
}
