name: lui_components
description: Flutter host for the shared LG LUI component gallery.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  lui_flutter_backend:
    path: ../../../platform/flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png
