(library
 (name lui_text_pango)
 (modules lui_text_pango)
 (enabled_if (= %{system} linux))
 (foreign_stubs
  (language c)
  (names lui_text_pango_stubs)
  (flags (:standard (:include c_flags.sexp))))
 (c_library_flags (:standard (:include c_libs.sexp))))

(rule
 (target c_flags.sexp)
 (action
  (with-stdout-to %{target}
   (bash
    "printf '(%s)' \"$(pkg-config --cflags pangocairo pangoft2 fontconfig)\""))))

(rule
 (target c_libs.sexp)
 (action
  (with-stdout-to %{target}
   (bash
    "printf '(%s)' \"$(pkg-config --libs pangocairo pangoft2 fontconfig)\""))))
