// Generated from schema/components.json. Do not edit by hand.
import Foundation

enum LUINodeKind: String, Decodable, Equatable {
    case row = "row"
    case column = "column"
    case grid = "grid"
    case stack = "stack"
    case panel = "panel"
    case card = "card"
    case box = "box"
    case text = "text"
    case heading = "heading"
    case paragraph = "paragraph"
    case label = "label"
    case button = "button"
    case toggleButton = "toggle-button"
    case toggle = "toggle"
    case radioGroup = "radio-group"
    case radio = "radio"
    case slider = "slider"
    case textInput = "text-input"
    case textArea = "text-area"
    case checkbox = "checkbox"
    case switchControl = "switch"
    case progress = "progress"
    case divider = "divider"
    case scroll = "scroll"
    case list = "list"
    case spacer = "spacer"
    case spinner = "spinner"
    case icon = "icon"
}

enum LUIProperty: String, Decodable, Hashable {
    case text = "text"
    case enabled = "enabled"
    case gap = "gap"
    case main = "main"
    case cross = "cross"
    case grow = "grow"
    case columns = "columns"
    case padding = "padding"
    case paddingHorizontal = "padding-horizontal"
    case paddingVertical = "padding-vertical"
    case background = "background"
    case foreground = "foreground"
    case borderColor = "border-color"
    case borderWidth = "border-width"
    case cornerRadius = "corner-radius"
    case width = "width"
    case height = "height"
    case minWidth = "min-width"
    case maxWidth = "max-width"
    case minHeight = "min-height"
    case maxHeight = "max-height"
    case placeholder = "placeholder"
    case readOnly = "read-only"
    case accessibilityLabel = "accessibility-label"
    case minLines = "min-lines"
    case maxLines = "max-lines"
    case styleClass = "style-class"
    case headingLevel = "heading-level"
    case labelledBy = "labelled-by"
    case describedBy = "described-by"
    case errorMessageBy = "error-message-by"
    case inputType = "input-type"
    case invalid = "invalid"
    case checked = "checked"
    case progressValue = "value"
    case minValue = "min-value"
    case maxValue = "max-value"
    case orientation = "orientation"
    case size = "size"
    case name = "name"
    case variant = "variant"
    case icon = "icon"
    case iconPlacement = "icon-placement"
    case selected = "selected"
    case autofocus = "autofocus"
    case holdEnabled = "hold-enabled"
    case changeEnabled = "change-enabled"
    case toggleEnabled = "toggle-enabled"
    case pressEnabled = "press-enabled"
}
