// Generated from schema/components.json. Do not edit by hand.
import Foundation

enum LUINodeKind: String, Decodable, Equatable {
    case root = "root"
    case row = "row"
    case column = "column"
    case grid = "grid"
    case stack = "stack"
    case edgeInset = "edge-inset"
    case overlay = "overlay"
    case viewThatFits = "view-that-fits"
    case panel = "panel"
    case card = "card"
    case alert = "alert"
    case bubble = "bubble"
    case box = "box"
    case text = "text"
    case heading = "heading"
    case paragraph = "paragraph"
    case label = "label"
    case button = "button"
    case toggleButton = "toggle-button"
    case toggle = "toggle"
    case radioGroup = "radio-group"
    case radio = "radio"
    case slider = "slider"
    case numberStepper = "number-stepper"
    case textField = "text-field"
    case secureField = "secure-field"
    case input = "input"
    case searchField = "search-field"
    case textarea = "textarea"
    case checkbox = "checkbox"
    case switchControl = "switch"
    case progress = "progress"
    case divider = "divider"
    case scroll = "scroll"
    case list = "list"
    case virtualList = "virtual-list"
    case tabs = "tabs"
    case bottomTabs = "bottom-tabs"
    case bottomTab = "bottom-tab"
    case buttonGroup = "button-group"
    case toggleGroup = "toggle-group"
    case spacer = "spacer"
    case spinner = "spinner"
    case icon = "icon"
    case select = "select"
    case combobox = "combobox"
    case dropdownMenu = "dropdown-menu"
    case contextMenu = "context-menu"
    case menuItem = "menu-item"
    case menuTrigger = "menu-trigger"
    case listItem = "list-item"
    case avatar = "avatar"
    case image = "image"
    case mediaSurface = "media-surface"
    case stepper = "stepper"
    case step = "step"
    case timeline = "timeline"
    case timelineItem = "timeline-item"
    case inputGroup = "input-group"
    case inputGroupActions = "input-group-actions"
    case breadcrumb = "breadcrumb"
    case pagination = "pagination"
    case accordion = "accordion"
    case table = "table"
    case tableRow = "table-row"
    case tableCell = "table-cell"
    case tree = "tree"
    case resizable = "resizable"
    case split = "split"
    case dialog = "dialog"
    case drawer = "drawer"
    case sheet = "sheet"
    case tooltip = "tooltip"
    case toast = "toast"
    case toolbar = "toolbar"
    case statusBar = "status-bar"
    case listSection = "list-section"
    case listSectionHeader = "list-section-header"
    case listSectionFooter = "list-section-footer"
    case swipeActions = "swipe-actions"
    case swipeAction = "swipe-action"
    case filePicker = "file-picker"
    case kbd = "kbd"
    case link = "link"
    case fileImage = "file-image"
    case filePreview = "file-preview"
}

enum LUIProperty: String, Decodable, Hashable {
    case text = "text"
    case enabled = "enabled"
    case gap = "gap"
    case main = "main"
    case cross = "cross"
    case grow = "grow"
    case columns = "columns"
    case padding = "padding"
    case paddingHorizontal = "padding-horizontal"
    case paddingVertical = "padding-vertical"
    case background = "background"
    case foreground = "foreground"
    case borderColor = "border-color"
    case borderWidth = "border-width"
    case cornerRadius = "corner-radius"
    case width = "width"
    case height = "height"
    case minWidth = "min-width"
    case maxWidth = "max-width"
    case minHeight = "min-height"
    case maxHeight = "max-height"
    case containerRelativeFrame = "container-relative-frame"
    case containerRelativeFrameInset = "container-relative-frame-inset"
    case placeholder = "placeholder"
    case accessibilityLabel = "accessibility-label"
    case accessibilityIdentifier = "accessibility-identifier"
    case styleClass = "style-class"
    case headingLevel = "heading-level"
    case checked = "checked"
    case progressValue = "value"
    case orientation = "orientation"
    case placement = "placement"
    case size = "size"
    case name = "name"
    case variant = "variant"
    case icon = "icon"
    case iconPlacement = "icon-placement"
    case selected = "selected"
    case autofocus = "autofocus"
    case submitOnEnter = "submit-on-enter"
    case longPressEnabled = "long-press-enabled"
    case changeEnabled = "change-enabled"
    case toggleEnabled = "toggle-enabled"
    case pressEnabled = "press-enabled"
    case submitEnabled = "submit-enabled"
    case doublePressEnabled = "double-press-enabled"
    case appearEnabled = "appear-enabled"
    case image = "image"
    case surface = "surface"
    case active = "active"
    case title = "title"
    case description = "description"
    case meta = "meta"
    case indicator = "indicator"
    case connector = "connector"
    case sourceX = "source-x"
    case sourceY = "source-y"
    case sourceWidth = "source-width"
    case sourceHeight = "source-height"
    case anchor = "anchor"
    case anchorAlignment = "anchor-alignment"
    case anchorOffset = "anchor-offset"
    case tooltipDelay = "tooltip-delay"
    case duration = "duration"
    case textAlignment = "text-alignment"
    case role = "role"
    case treeLevel = "tree-level"
    case expanded = "expanded"
    case resizeDuration = "resize-duration"
    case resizeEasing = "resize-easing"
    case resizeOrigin = "resize-origin"
    case theme = "theme"
    case themeMode = "theme-mode"
    case key = "key"
    case separator = "separator"
    case style = "style"
    case scrollTarget = "scroll-target"
    case scrollAnchor = "scroll-anchor"
    case scrollToken = "scroll-token"
    case scrollAnimated = "scroll-animated"
    case trackVisibleRange = "track-visible-range"
    case edge = "edge"
    case request = "request"
    case types = "types"
    case multiple = "multiple"
    case source = "source"
    case completion = "completion"
    case minValue = "min"
    case maxValue = "max"
    case stepValue = "step"
    case detents = "detents"
    case sizing = "sizing"
    case path = "path"
    case url = "url"
    case maxPixelSize = "max-pixel-size"
    case imageFit = "image-fit"
    case visible = "visible"
    case alignment = "alignment"
    case pointerEnabled = "pointer-enabled"
    case dataAttrs = "data-attrs"
    case asTag = "as"
}

enum LUISchemaMatrix {
    static let restrictive: [LUINodeKind: Set<LUIProperty>] = [
        .accordion: [.text, .selected, .toggleEnabled, .height, .pointerEnabled],
        .stepper: [.active, .accessibilityLabel, .pointerEnabled],
        .step: [.text, .pointerEnabled],
        .timeline: [.gap, .grow, .accessibilityLabel, .pointerEnabled],
        .timelineItem: [.title, .description, .meta, .indicator, .icon, .variant, .connector, .selected, .pressEnabled, .pointerEnabled],
        .inputGroup: [.accessibilityLabel, .width, .height, .minWidth, .grow, .pointerEnabled],
        .inputGroupActions: [.gap, .pointerEnabled],
        .toast: [.duration, .accessibilityLabel, .styleClass, .dataAttrs, .pointerEnabled],
        .toolbar: [.orientation, .accessibilityLabel, .gap, .styleClass, .dataAttrs, .placement, .pointerEnabled],
        .bottomTabs: [.accessibilityLabel, .styleClass, .dataAttrs, .grow, .width, .height, .minWidth, .maxWidth, .minHeight, .maxHeight, .pointerEnabled],
        .bottomTab: [.title, .icon, .selected, .enabled, .pressEnabled, .pointerEnabled],
        .menuTrigger: [.text, .icon, .accessibilityLabel, .enabled, .foreground, .styleClass, .dataAttrs, .pointerEnabled],
        .listSection: [.key, .separator, .pointerEnabled],
        .swipeActions: [],
        .swipeAction: [.text, .icon, .variant, .edge, .enabled, .background, .pressEnabled, .pointerEnabled],
        .filePicker: [.request, .types, .multiple, .source, .completion, .enabled, .appearEnabled, .pointerEnabled],
        .filePreview: [.path, .pointerEnabled],
        .kbd: [.text, .styleClass, .dataAttrs, .pointerEnabled],
    ]

    static let extra: [LUINodeKind: Set<LUIProperty>] = [
        .dialog: [.description],
    ]
}
