(* Generated by tooling/generate_extension_api.mjs. Do not edit by hand. *)

open Lui_protocol





let apple_map_schema =
  Lui_extension.component "apple-map" [ { Lui_protocol.profile_os = MacOS; Lui_protocol.profile_host = SwiftUIHost }; { Lui_protocol.profile_os = IOS; Lui_protocol.profile_host = SwiftUIHost } ]
    false
    [ "apple-map-marker" ]
    [ Lui_extension.property "latitude" Lui_extension.FloatScalar true None; Lui_extension.property "longitude" Lui_extension.FloatScalar true None; Lui_extension.property "latitude-delta" Lui_extension.FloatScalar true None; Lui_extension.property "longitude-delta" Lui_extension.FloatScalar true None ]
    [  ]

let apple_map_marker_schema =
  Lui_extension.component "apple-map-marker" [ { Lui_protocol.profile_os = MacOS; Lui_protocol.profile_host = SwiftUIHost }; { Lui_protocol.profile_os = IOS; Lui_protocol.profile_host = SwiftUIHost } ]
    false
    [  ]
    [ Lui_extension.property "title" Lui_extension.StringScalar true None; Lui_extension.property "latitude" Lui_extension.FloatScalar true None; Lui_extension.property "longitude" Lui_extension.FloatScalar true None ]
    [  ]

let gallery_accent_schema =
  Lui_extension.tweak "gallery-accent" [ { Lui_protocol.profile_os = AndroidOS; Lui_protocol.profile_host = FlutterHost }; { Lui_protocol.profile_os = IOS; Lui_protocol.profile_host = FlutterHost }; { Lui_protocol.profile_os = IOS; Lui_protocol.profile_host = SwiftUIHost }; { Lui_protocol.profile_os = LinuxOS; Lui_protocol.profile_host = FlutterHost }; { Lui_protocol.profile_os = MacOS; Lui_protocol.profile_host = FlutterHost }; { Lui_protocol.profile_os = MacOS; Lui_protocol.profile_host = SwiftUIHost }; { Lui_protocol.profile_os = WebOS; Lui_protocol.profile_host = WebHost }; { Lui_protocol.profile_os = WindowsOS; Lui_protocol.profile_host = FlutterHost } ]
    [  ]

let registry () =
  let registry = Lui_extension.registry () in
  Lui_extension.register_component registry apple_map_schema;
  Lui_extension.register_component registry apple_map_marker_schema;
  Lui_extension.register_tweak registry gallery_accent_schema;
  Lui_extension.freeze registry;
  registry

let apple_map ?key ~latitude ~longitude ~latitude_delta ~longitude_delta ?latitude_signal ?longitude_signal ?latitude_delta_signal ?longitude_delta_signal (children : Lui_elements.t list) : Lui_elements.t =
 fun context parent ->
  let node = Lui_ui.extension context "apple-map" in
  Option.iter (Lui_ui.key context node) key;
  Option.iter
    (fun value ->
       Lui_ui.extension_property context node "latitude"
         (FloatValue value))
    (Some latitude);
  Option.iter
    (fun signal ->
       Lui_ui.extension_property_signal context node "latitude"
         (Signal.map (fun value -> FloatValue value) signal))
    latitude_signal;
  Option.iter
    (fun value ->
       Lui_ui.extension_property context node "longitude"
         (FloatValue value))
    (Some longitude);
  Option.iter
    (fun signal ->
       Lui_ui.extension_property_signal context node "longitude"
         (Signal.map (fun value -> FloatValue value) signal))
    longitude_signal;
  Option.iter
    (fun value ->
       Lui_ui.extension_property context node "latitude-delta"
         (FloatValue value))
    (Some latitude_delta);
  Option.iter
    (fun signal ->
       Lui_ui.extension_property_signal context node "latitude-delta"
         (Signal.map (fun value -> FloatValue value) signal))
    latitude_delta_signal;
  Option.iter
    (fun value ->
       Lui_ui.extension_property context node "longitude-delta"
         (FloatValue value))
    (Some longitude_delta);
  Option.iter
    (fun signal ->
       Lui_ui.extension_property_signal context node "longitude-delta"
         (Signal.map (fun value -> FloatValue value) signal))
    longitude_delta_signal;

  (match parent with
   | Some parent -> Lui_ui.append context parent node
   | None -> ());
  Lui_elements.mount_children context node children;
  node

let apple_map_marker ?key ~title ~latitude ~longitude ?title_signal ?latitude_signal ?longitude_signal () : Lui_elements.t =
 fun context parent ->
  let node = Lui_ui.extension context "apple-map-marker" in
  Option.iter (Lui_ui.key context node) key;
  Option.iter
    (fun value ->
       Lui_ui.extension_property context node "title"
         (StringValue value))
    (Some title);
  Option.iter
    (fun signal ->
       Lui_ui.extension_property_signal context node "title"
         (Signal.map (fun value -> StringValue value) signal))
    title_signal;
  Option.iter
    (fun value ->
       Lui_ui.extension_property context node "latitude"
         (FloatValue value))
    (Some latitude);
  Option.iter
    (fun signal ->
       Lui_ui.extension_property_signal context node "latitude"
         (Signal.map (fun value -> FloatValue value) signal))
    latitude_signal;
  Option.iter
    (fun value ->
       Lui_ui.extension_property context node "longitude"
         (FloatValue value))
    (Some longitude);
  Option.iter
    (fun signal ->
       Lui_ui.extension_property_signal context node "longitude"
         (Signal.map (fun value -> FloatValue value) signal))
    longitude_signal;

  (match parent with
   | Some parent -> Lui_ui.append context parent node
   | None -> ());

  node
