(rule
 (target todos_bridge.ml)
 (deps
  ../../../lg/lui/lui_native.state
  (source_tree ../../../lg/lui/backend)
  (source_tree ../../../examples/todos/lg/todos)
  (source_tree .)
  %{bin:lg})
 (action
  (run
   %{bin:lg}
   --target native
   --compile-files-from ../../../lg/lui/lui_native.state
   ../../../lg/lui/backend/retained
   ../../../lg/lui/backend/flutter
   ../../../examples/todos/lg/todos
   .
   -o %{target})))

(rule
 (target todos_bridge_complete.o)
 (deps todos_bridge.ml)
 (action
  (run
   ocamlfind ocamlopt
   -package lg.edn-backend.native,lg.runtime,lg.rrbvec
   -linkpkg
   -output-complete-obj
   -o %{target}
   %{dep:todos_bridge.ml})))

(rule
 (target liblui_todos.dylib)
 (deps todos_bridge_complete.o lui_ocaml_bridge.c)
 (action
  (run
   clang
   -dynamiclib
   -o %{target}
   %{dep:lui_ocaml_bridge.c}
   %{dep:todos_bridge_complete.o}
   -I %{ocaml_where}
   -lpthread)))
