// Export the OCaml protocol's admission rules for the portable Rust mirror.
// No Dune declaration is needed: the protocol module is self-contained.
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const schema = JSON.parse(readFileSync(resolve(root, 'schema/components.json'), 'utf8'));
const source = readFileSync(resolve(root, 'src/lui_protocol.ml'), 'utf8');
const destination = resolve(root, 'platform/gpui/crates/lui-core/src/protocol_rules.rs');
const directory = mkdtempSync(resolve(tmpdir(), 'lui-protocol-'));
try {
  writeFileSync(resolve(directory, 'lui_protocol.ml'), source);
  const strings = [...new Set([...source.matchAll(/"([^"\\]*)"/g)].map(m => m[1]))]
    .filter(s => !s.includes('\n'));
  const entries = (entries, field) => entries.map(e => `(${e.lg}, ${JSON.stringify(e[field])})`).join(';\n');
  writeFileSync(resolve(directory, 'export.ml'), `open Lui_protocol
let kinds = [${entries(schema.nodeKinds, 'lg')}]
let properties = [${entries(schema.properties, 'lg')}]
let strings = [${strings.map(JSON.stringify).join(';')}]
let () =
  List.iter (fun (kind, name) ->
    Printf.printf "kind %s" name;
    List.iter (fun (property, _) -> Printf.printf " %d" (if property_supported kind property then 1 else 0)) properties;
    print_newline ();
    Printf.printf "host %s %d\\n" name (if context_menu_host_kind kind then 1 else 0);
    Printf.printf "child %s" name;
    List.iter (fun (child, _) -> Printf.printf " %d" (if can_contain_children kind && child_kind_supported kind child then 1 else 0)) kinds;
    print_newline ()) kinds;
  List.iter (fun (property, name) ->
    let free = property_value_supported property (StringValue "arbitrary value without an enum") in
    Printf.printf "string %s %s" name (if free then "free" else "enum");
    List.iter (fun value -> if property_value_supported property (StringValue value) then
      Printf.printf " %s" (String.escaped value)) strings;
    print_newline ()) properties
`);
  execFileSync('opam', ['exec', '--', 'ocamlopt', '-o', 'export', 'lui_protocol.ml', 'export.ml'], { cwd: directory, stdio: ['ignore', 'ignore', 'pipe'] });
  const lines = execFileSync(resolve(directory, 'export'), { cwd: directory, encoding: 'utf8' }).trim().split('\n');
  // Spaces in enumerated strings are not part of the protocol vocabulary.
  const masks = category => lines.filter(s => s.startsWith(category + ' ')).map(s => {
    const [, name, ...bits] = s.split(' ');
    const mask = bits.reduce((mask, bit, index) => bit === '1' ? mask | (1n << BigInt(index)) : mask, 0n);
    return `        NodeKind::${name} => 0x${mask.toString(16)},`;
  }).join('\n');
  const enums = lines.filter(s => s.startsWith('string ')).map(s => {
    const [, name, mode, ...values] = s.split(' ');
    if (mode === 'free') return `        Property::${name} => true,`;
    const valid = values.filter(v => v.length > 0).map(JSON.stringify);
    return valid.length ? `        Property::${name} => [${valid.join(', ')}].contains(&value),` : null;
  }).filter(Boolean).join('\n');
  const result = `// Generated by tooling/generate_gpui_protocol_rules.mjs from src/lui_protocol.ml.
// Do not edit by hand. Enum order follows schema/components.json.
use crate::wire_schema::{NodeKind, Property};

pub(crate) fn property_supported(kind: NodeKind, property: Property) -> bool {
    let mask: u128 = match kind {
${masks('kind')}
    };
    mask & (1_u128 << property as u32) != 0
}

fn child_mask(parent: NodeKind) -> u128 {
    match parent {
${masks('child')}
    }
}

pub(crate) fn container_supported(kind: NodeKind) -> bool {
    child_mask(kind) != 0
}

pub(crate) fn child_supported(parent: NodeKind, child: NodeKind) -> bool {
    child_mask(parent) & (1_u128 << child as u32) != 0
}

pub(crate) fn context_menu_host(kind: NodeKind) -> bool {
    matches!(kind, ${lines.filter(s => s.startsWith('host ') && s.endsWith(' 1')).map(s => 'NodeKind::' + s.split(' ')[1]).join(' | ')})
}

pub(crate) fn string_supported(property: Property, value: &str) -> bool {
    match property {
${enums}
        _ => false,
    }
}
`;
  if (process.argv.includes('--check')) {
    const normalize = s => {
      const tokens = s.match(/"(?:[^"\\]|\\.)*"|[^\s]/g) ?? [];
      return tokens.filter((token, index) => token !== ',' || ![')', ']', '}'].includes(tokens[index + 1])).join('');
    };
    if (normalize(readFileSync(destination, 'utf8')) !== normalize(result)) throw new Error('GPUI protocol rules are stale; regenerate them');
  } else writeFileSync(destination, result);
} finally { rmSync(directory, { recursive: true, force: true }); }
