// Generated from schema/components.json. Do not edit by hand.

#nullable enable

using System.Collections.Generic;

namespace LUI
{
    public enum LUINodeKind
    {
        Root,
        Row,
        Column,
        Grid,
        Stack,
        Panel,
        Card,
        Alert,
        Bubble,
        Box,
        Text,
        Heading,
        Paragraph,
        Label,
        Button,
        ToggleButton,
        Toggle,
        RadioGroup,
        Radio,
        Slider,
        TextField,
        SecureField,
        Input,
        SearchField,
        Textarea,
        Checkbox,
        SwitchControl,
        Progress,
        Divider,
        Scroll,
        ListContainer,
        VirtualList,
        Tabs,
        BottomTabs,
        BottomTab,
        ButtonGroup,
        ToggleGroup,
        Spacer,
        Spinner,
        Icon,
        Select,
        Combobox,
        DropdownMenu,
        ContextMenu,
        MenuItem,
        ListItem,
        Avatar,
        Image,
        MediaSurface,
        Stepper,
        Step,
        Timeline,
        TimelineItem,
        InputGroup,
        InputGroupActions,
        Breadcrumb,
        Pagination,
        Accordion,
        Table,
        TableRow,
        TableCell,
        Tree,
        Resizable,
        Split,
        Dialog,
        Drawer,
        Sheet,
        Tooltip,
        Toast,
        Toolbar,
        StatusBar,
    }

    public enum LUIProperty
    {
        TextValue,
        Enabled,
        Gap,
        MainAlignment,
        CrossAlignment,
        GrowValue,
        GridColumns,
        PaddingValue,
        PaddingHorizontal,
        PaddingVertical,
        BackgroundValue,
        ForegroundValue,
        BorderColorValue,
        BorderWidth,
        CornerRadius,
        WidthValue,
        HeightValue,
        MinWidth,
        MaxWidth,
        MinHeight,
        MaxHeight,
        ContainerRelativeFrameValue,
        ContainerRelativeFrameInset,
        PlaceholderValue,
        AccessibilityLabel,
        AccessibilityIdentifier,
        StyleClass,
        HeadingLevel,
        Checked,
        ProgressValue,
        OrientationValue,
        SizeValue,
        IconName,
        VariantValue,
        InlineIconName,
        IconPlacementValue,
        Selected,
        Autofocus,
        SubmitOnEnter,
        LongPressEnabled,
        ChangeEnabled,
        ToggleEnabled,
        PressEnabled,
        SubmitEnabled,
        DoublePressEnabled,
        AppearEnabled,
        ImageIdValue,
        SurfaceIdValue,
        ActiveIndex,
        TitleValue,
        DescriptionValue,
        MetaValue,
        IndicatorValue,
        Connector,
        SourceX,
        SourceY,
        SourceWidth,
        SourceHeight,
        AnchorValue,
        AnchorAlignmentValue,
        AnchorOffset,
        TooltipDelay,
        DurationValue,
        TextAlignment,
        RoleValue,
        TreeLevel,
        Expanded,
        ResizeDuration,
        ResizeEasing,
        ResizeOrigin,
    }

    public static class LUIWireSchema
    {
        private static readonly Dictionary<string, LUINodeKind> NodeKindsByWireName =
            new Dictionary<string, LUINodeKind>
        {
            { "root", LUINodeKind.Root },
            { "row", LUINodeKind.Row },
            { "column", LUINodeKind.Column },
            { "grid", LUINodeKind.Grid },
            { "stack", LUINodeKind.Stack },
            { "panel", LUINodeKind.Panel },
            { "card", LUINodeKind.Card },
            { "alert", LUINodeKind.Alert },
            { "bubble", LUINodeKind.Bubble },
            { "box", LUINodeKind.Box },
            { "text", LUINodeKind.Text },
            { "heading", LUINodeKind.Heading },
            { "paragraph", LUINodeKind.Paragraph },
            { "label", LUINodeKind.Label },
            { "button", LUINodeKind.Button },
            { "toggle-button", LUINodeKind.ToggleButton },
            { "toggle", LUINodeKind.Toggle },
            { "radio-group", LUINodeKind.RadioGroup },
            { "radio", LUINodeKind.Radio },
            { "slider", LUINodeKind.Slider },
            { "text-field", LUINodeKind.TextField },
            { "secure-field", LUINodeKind.SecureField },
            { "input", LUINodeKind.Input },
            { "search-field", LUINodeKind.SearchField },
            { "textarea", LUINodeKind.Textarea },
            { "checkbox", LUINodeKind.Checkbox },
            { "switch", LUINodeKind.SwitchControl },
            { "progress", LUINodeKind.Progress },
            { "divider", LUINodeKind.Divider },
            { "scroll", LUINodeKind.Scroll },
            { "list", LUINodeKind.ListContainer },
            { "virtual-list", LUINodeKind.VirtualList },
            { "tabs", LUINodeKind.Tabs },
            { "bottom-tabs", LUINodeKind.BottomTabs },
            { "bottom-tab", LUINodeKind.BottomTab },
            { "button-group", LUINodeKind.ButtonGroup },
            { "toggle-group", LUINodeKind.ToggleGroup },
            { "spacer", LUINodeKind.Spacer },
            { "spinner", LUINodeKind.Spinner },
            { "icon", LUINodeKind.Icon },
            { "select", LUINodeKind.Select },
            { "combobox", LUINodeKind.Combobox },
            { "dropdown-menu", LUINodeKind.DropdownMenu },
            { "context-menu", LUINodeKind.ContextMenu },
            { "menu-item", LUINodeKind.MenuItem },
            { "list-item", LUINodeKind.ListItem },
            { "avatar", LUINodeKind.Avatar },
            { "image", LUINodeKind.Image },
            { "media-surface", LUINodeKind.MediaSurface },
            { "stepper", LUINodeKind.Stepper },
            { "step", LUINodeKind.Step },
            { "timeline", LUINodeKind.Timeline },
            { "timeline-item", LUINodeKind.TimelineItem },
            { "input-group", LUINodeKind.InputGroup },
            { "input-group-actions", LUINodeKind.InputGroupActions },
            { "breadcrumb", LUINodeKind.Breadcrumb },
            { "pagination", LUINodeKind.Pagination },
            { "accordion", LUINodeKind.Accordion },
            { "table", LUINodeKind.Table },
            { "table-row", LUINodeKind.TableRow },
            { "table-cell", LUINodeKind.TableCell },
            { "tree", LUINodeKind.Tree },
            { "resizable", LUINodeKind.Resizable },
            { "split", LUINodeKind.Split },
            { "dialog", LUINodeKind.Dialog },
            { "drawer", LUINodeKind.Drawer },
            { "sheet", LUINodeKind.Sheet },
            { "tooltip", LUINodeKind.Tooltip },
            { "toast", LUINodeKind.Toast },
            { "toolbar", LUINodeKind.Toolbar },
            { "status-bar", LUINodeKind.StatusBar },
        };

        private static readonly Dictionary<string, LUIProperty> PropertiesByWireName =
            new Dictionary<string, LUIProperty>
        {
            { "text", LUIProperty.TextValue },
            { "enabled", LUIProperty.Enabled },
            { "gap", LUIProperty.Gap },
            { "main", LUIProperty.MainAlignment },
            { "cross", LUIProperty.CrossAlignment },
            { "grow", LUIProperty.GrowValue },
            { "columns", LUIProperty.GridColumns },
            { "padding", LUIProperty.PaddingValue },
            { "padding-horizontal", LUIProperty.PaddingHorizontal },
            { "padding-vertical", LUIProperty.PaddingVertical },
            { "background", LUIProperty.BackgroundValue },
            { "foreground", LUIProperty.ForegroundValue },
            { "border-color", LUIProperty.BorderColorValue },
            { "border-width", LUIProperty.BorderWidth },
            { "corner-radius", LUIProperty.CornerRadius },
            { "width", LUIProperty.WidthValue },
            { "height", LUIProperty.HeightValue },
            { "min-width", LUIProperty.MinWidth },
            { "max-width", LUIProperty.MaxWidth },
            { "min-height", LUIProperty.MinHeight },
            { "max-height", LUIProperty.MaxHeight },
            { "container-relative-frame", LUIProperty.ContainerRelativeFrameValue },
            { "container-relative-frame-inset", LUIProperty.ContainerRelativeFrameInset },
            { "placeholder", LUIProperty.PlaceholderValue },
            { "accessibility-label", LUIProperty.AccessibilityLabel },
            { "accessibility-identifier", LUIProperty.AccessibilityIdentifier },
            { "style-class", LUIProperty.StyleClass },
            { "heading-level", LUIProperty.HeadingLevel },
            { "checked", LUIProperty.Checked },
            { "value", LUIProperty.ProgressValue },
            { "orientation", LUIProperty.OrientationValue },
            { "size", LUIProperty.SizeValue },
            { "name", LUIProperty.IconName },
            { "variant", LUIProperty.VariantValue },
            { "icon", LUIProperty.InlineIconName },
            { "icon-placement", LUIProperty.IconPlacementValue },
            { "selected", LUIProperty.Selected },
            { "autofocus", LUIProperty.Autofocus },
            { "submit-on-enter", LUIProperty.SubmitOnEnter },
            { "long-press-enabled", LUIProperty.LongPressEnabled },
            { "change-enabled", LUIProperty.ChangeEnabled },
            { "toggle-enabled", LUIProperty.ToggleEnabled },
            { "press-enabled", LUIProperty.PressEnabled },
            { "submit-enabled", LUIProperty.SubmitEnabled },
            { "double-press-enabled", LUIProperty.DoublePressEnabled },
            { "appear-enabled", LUIProperty.AppearEnabled },
            { "image", LUIProperty.ImageIdValue },
            { "surface", LUIProperty.SurfaceIdValue },
            { "active", LUIProperty.ActiveIndex },
            { "title", LUIProperty.TitleValue },
            { "description", LUIProperty.DescriptionValue },
            { "meta", LUIProperty.MetaValue },
            { "indicator", LUIProperty.IndicatorValue },
            { "connector", LUIProperty.Connector },
            { "source-x", LUIProperty.SourceX },
            { "source-y", LUIProperty.SourceY },
            { "source-width", LUIProperty.SourceWidth },
            { "source-height", LUIProperty.SourceHeight },
            { "anchor", LUIProperty.AnchorValue },
            { "anchor-alignment", LUIProperty.AnchorAlignmentValue },
            { "anchor-offset", LUIProperty.AnchorOffset },
            { "tooltip-delay", LUIProperty.TooltipDelay },
            { "duration", LUIProperty.DurationValue },
            { "text-alignment", LUIProperty.TextAlignment },
            { "role", LUIProperty.RoleValue },
            { "tree-level", LUIProperty.TreeLevel },
            { "expanded", LUIProperty.Expanded },
            { "resize-duration", LUIProperty.ResizeDuration },
            { "resize-easing", LUIProperty.ResizeEasing },
            { "resize-origin", LUIProperty.ResizeOrigin },
        };

        public static string WireName(this LUINodeKind kind) => kind switch
        {
            LUINodeKind.Root => "root",
            LUINodeKind.Row => "row",
            LUINodeKind.Column => "column",
            LUINodeKind.Grid => "grid",
            LUINodeKind.Stack => "stack",
            LUINodeKind.Panel => "panel",
            LUINodeKind.Card => "card",
            LUINodeKind.Alert => "alert",
            LUINodeKind.Bubble => "bubble",
            LUINodeKind.Box => "box",
            LUINodeKind.Text => "text",
            LUINodeKind.Heading => "heading",
            LUINodeKind.Paragraph => "paragraph",
            LUINodeKind.Label => "label",
            LUINodeKind.Button => "button",
            LUINodeKind.ToggleButton => "toggle-button",
            LUINodeKind.Toggle => "toggle",
            LUINodeKind.RadioGroup => "radio-group",
            LUINodeKind.Radio => "radio",
            LUINodeKind.Slider => "slider",
            LUINodeKind.TextField => "text-field",
            LUINodeKind.SecureField => "secure-field",
            LUINodeKind.Input => "input",
            LUINodeKind.SearchField => "search-field",
            LUINodeKind.Textarea => "textarea",
            LUINodeKind.Checkbox => "checkbox",
            LUINodeKind.SwitchControl => "switch",
            LUINodeKind.Progress => "progress",
            LUINodeKind.Divider => "divider",
            LUINodeKind.Scroll => "scroll",
            LUINodeKind.ListContainer => "list",
            LUINodeKind.VirtualList => "virtual-list",
            LUINodeKind.Tabs => "tabs",
            LUINodeKind.BottomTabs => "bottom-tabs",
            LUINodeKind.BottomTab => "bottom-tab",
            LUINodeKind.ButtonGroup => "button-group",
            LUINodeKind.ToggleGroup => "toggle-group",
            LUINodeKind.Spacer => "spacer",
            LUINodeKind.Spinner => "spinner",
            LUINodeKind.Icon => "icon",
            LUINodeKind.Select => "select",
            LUINodeKind.Combobox => "combobox",
            LUINodeKind.DropdownMenu => "dropdown-menu",
            LUINodeKind.ContextMenu => "context-menu",
            LUINodeKind.MenuItem => "menu-item",
            LUINodeKind.ListItem => "list-item",
            LUINodeKind.Avatar => "avatar",
            LUINodeKind.Image => "image",
            LUINodeKind.MediaSurface => "media-surface",
            LUINodeKind.Stepper => "stepper",
            LUINodeKind.Step => "step",
            LUINodeKind.Timeline => "timeline",
            LUINodeKind.TimelineItem => "timeline-item",
            LUINodeKind.InputGroup => "input-group",
            LUINodeKind.InputGroupActions => "input-group-actions",
            LUINodeKind.Breadcrumb => "breadcrumb",
            LUINodeKind.Pagination => "pagination",
            LUINodeKind.Accordion => "accordion",
            LUINodeKind.Table => "table",
            LUINodeKind.TableRow => "table-row",
            LUINodeKind.TableCell => "table-cell",
            LUINodeKind.Tree => "tree",
            LUINodeKind.Resizable => "resizable",
            LUINodeKind.Split => "split",
            LUINodeKind.Dialog => "dialog",
            LUINodeKind.Drawer => "drawer",
            LUINodeKind.Sheet => "sheet",
            LUINodeKind.Tooltip => "tooltip",
            LUINodeKind.Toast => "toast",
            LUINodeKind.Toolbar => "toolbar",
            LUINodeKind.StatusBar => "status-bar",
            _ => "unknown",
        };

        public static bool TryDecodeNodeKind(string? name, out LUINodeKind kind) =>
            NodeKindsByWireName.TryGetValue(name ?? "", out kind);

        public static bool IsStandardNodeName(string? name) =>
            TryDecodeNodeKind(name, out _);

        public static bool IsContainerKind(LUINodeKind kind) => kind switch
        {
            LUINodeKind.Root or
            LUINodeKind.Row or
            LUINodeKind.Column or
            LUINodeKind.Grid or
            LUINodeKind.Stack or
            LUINodeKind.Panel or
            LUINodeKind.Card or
            LUINodeKind.Alert or
            LUINodeKind.Bubble or
            LUINodeKind.Box or
            LUINodeKind.RadioGroup or
            LUINodeKind.Scroll or
            LUINodeKind.ListContainer or
            LUINodeKind.VirtualList or
            LUINodeKind.Tabs or
            LUINodeKind.BottomTabs or
            LUINodeKind.BottomTab or
            LUINodeKind.ButtonGroup or
            LUINodeKind.ToggleGroup or
            LUINodeKind.DropdownMenu or
            LUINodeKind.ContextMenu or
            LUINodeKind.MenuItem or
            LUINodeKind.ListItem or
            LUINodeKind.Stepper or
            LUINodeKind.Timeline or
            LUINodeKind.InputGroup or
            LUINodeKind.InputGroupActions or
            LUINodeKind.Breadcrumb or
            LUINodeKind.Pagination or
            LUINodeKind.Accordion or
            LUINodeKind.Table or
            LUINodeKind.TableRow or
            LUINodeKind.Tree or
            LUINodeKind.Resizable or
            LUINodeKind.Split or
            LUINodeKind.Dialog or
            LUINodeKind.Drawer or
            LUINodeKind.Sheet or
            LUINodeKind.Toast or
            LUINodeKind.Toolbar => true,
            _ => false,
        };

        public static string WireName(this LUIProperty property) => property switch
        {
            LUIProperty.TextValue => "text",
            LUIProperty.Enabled => "enabled",
            LUIProperty.Gap => "gap",
            LUIProperty.MainAlignment => "main",
            LUIProperty.CrossAlignment => "cross",
            LUIProperty.GrowValue => "grow",
            LUIProperty.GridColumns => "columns",
            LUIProperty.PaddingValue => "padding",
            LUIProperty.PaddingHorizontal => "padding-horizontal",
            LUIProperty.PaddingVertical => "padding-vertical",
            LUIProperty.BackgroundValue => "background",
            LUIProperty.ForegroundValue => "foreground",
            LUIProperty.BorderColorValue => "border-color",
            LUIProperty.BorderWidth => "border-width",
            LUIProperty.CornerRadius => "corner-radius",
            LUIProperty.WidthValue => "width",
            LUIProperty.HeightValue => "height",
            LUIProperty.MinWidth => "min-width",
            LUIProperty.MaxWidth => "max-width",
            LUIProperty.MinHeight => "min-height",
            LUIProperty.MaxHeight => "max-height",
            LUIProperty.ContainerRelativeFrameValue => "container-relative-frame",
            LUIProperty.ContainerRelativeFrameInset => "container-relative-frame-inset",
            LUIProperty.PlaceholderValue => "placeholder",
            LUIProperty.AccessibilityLabel => "accessibility-label",
            LUIProperty.AccessibilityIdentifier => "accessibility-identifier",
            LUIProperty.StyleClass => "style-class",
            LUIProperty.HeadingLevel => "heading-level",
            LUIProperty.Checked => "checked",
            LUIProperty.ProgressValue => "value",
            LUIProperty.OrientationValue => "orientation",
            LUIProperty.SizeValue => "size",
            LUIProperty.IconName => "name",
            LUIProperty.VariantValue => "variant",
            LUIProperty.InlineIconName => "icon",
            LUIProperty.IconPlacementValue => "icon-placement",
            LUIProperty.Selected => "selected",
            LUIProperty.Autofocus => "autofocus",
            LUIProperty.SubmitOnEnter => "submit-on-enter",
            LUIProperty.LongPressEnabled => "long-press-enabled",
            LUIProperty.ChangeEnabled => "change-enabled",
            LUIProperty.ToggleEnabled => "toggle-enabled",
            LUIProperty.PressEnabled => "press-enabled",
            LUIProperty.SubmitEnabled => "submit-enabled",
            LUIProperty.DoublePressEnabled => "double-press-enabled",
            LUIProperty.AppearEnabled => "appear-enabled",
            LUIProperty.ImageIdValue => "image",
            LUIProperty.SurfaceIdValue => "surface",
            LUIProperty.ActiveIndex => "active",
            LUIProperty.TitleValue => "title",
            LUIProperty.DescriptionValue => "description",
            LUIProperty.MetaValue => "meta",
            LUIProperty.IndicatorValue => "indicator",
            LUIProperty.Connector => "connector",
            LUIProperty.SourceX => "source-x",
            LUIProperty.SourceY => "source-y",
            LUIProperty.SourceWidth => "source-width",
            LUIProperty.SourceHeight => "source-height",
            LUIProperty.AnchorValue => "anchor",
            LUIProperty.AnchorAlignmentValue => "anchor-alignment",
            LUIProperty.AnchorOffset => "anchor-offset",
            LUIProperty.TooltipDelay => "tooltip-delay",
            LUIProperty.DurationValue => "duration",
            LUIProperty.TextAlignment => "text-alignment",
            LUIProperty.RoleValue => "role",
            LUIProperty.TreeLevel => "tree-level",
            LUIProperty.Expanded => "expanded",
            LUIProperty.ResizeDuration => "resize-duration",
            LUIProperty.ResizeEasing => "resize-easing",
            LUIProperty.ResizeOrigin => "resize-origin",
            _ => "unknown",
        };

        public static bool TryDecodeProperty(string? name, out LUIProperty property) =>
            PropertiesByWireName.TryGetValue(name ?? "", out property);

        private static HashSet<LUIProperty> Set(params LUIProperty[] values) =>
            new HashSet<LUIProperty>(values);

        public static readonly IReadOnlyDictionary<LUINodeKind, IReadOnlySet<LUIProperty>> RestrictiveMatrix =
            new Dictionary<LUINodeKind, IReadOnlySet<LUIProperty>>
        {
            { LUINodeKind.Accordion, Set(LUIProperty.TextValue, LUIProperty.Selected, LUIProperty.ToggleEnabled, LUIProperty.HeightValue) },
            { LUINodeKind.Stepper, Set(LUIProperty.ActiveIndex, LUIProperty.AccessibilityLabel) },
            { LUINodeKind.Step, Set(LUIProperty.TextValue) },
            { LUINodeKind.Timeline, Set(LUIProperty.Gap, LUIProperty.GrowValue, LUIProperty.AccessibilityLabel) },
            { LUINodeKind.TimelineItem, Set(LUIProperty.TitleValue, LUIProperty.DescriptionValue, LUIProperty.MetaValue, LUIProperty.IndicatorValue, LUIProperty.InlineIconName, LUIProperty.VariantValue, LUIProperty.Connector, LUIProperty.Selected, LUIProperty.PressEnabled) },
            { LUINodeKind.InputGroup, Set(LUIProperty.AccessibilityLabel, LUIProperty.WidthValue, LUIProperty.HeightValue, LUIProperty.MinWidth, LUIProperty.GrowValue) },
            { LUINodeKind.InputGroupActions, Set(LUIProperty.Gap) },
            { LUINodeKind.Toast, Set(LUIProperty.DurationValue, LUIProperty.AccessibilityLabel, LUIProperty.StyleClass) },
            { LUINodeKind.Toolbar, Set(LUIProperty.OrientationValue, LUIProperty.AccessibilityLabel, LUIProperty.Gap, LUIProperty.StyleClass) },
            { LUINodeKind.BottomTabs, Set(LUIProperty.AccessibilityLabel, LUIProperty.StyleClass, LUIProperty.GrowValue, LUIProperty.WidthValue, LUIProperty.HeightValue, LUIProperty.MinWidth, LUIProperty.MaxWidth, LUIProperty.MinHeight, LUIProperty.MaxHeight) },
            { LUINodeKind.BottomTab, Set(LUIProperty.TitleValue, LUIProperty.InlineIconName, LUIProperty.Selected, LUIProperty.Enabled, LUIProperty.PressEnabled) },
        };

        public static readonly IReadOnlyDictionary<LUINodeKind, IReadOnlySet<LUIProperty>> ExtraMatrix =
            new Dictionary<LUINodeKind, IReadOnlySet<LUIProperty>>
        {
            { LUINodeKind.Dialog, Set(LUIProperty.DescriptionValue) },
        };
    }
}
